import type { PGPerson } from "./policyGeniusPeopleSegment";

/**
 * BREEZE_REAL_LEADS — 39 real Breeze Insurance leads
 * Transformed from breezeLeads.ts to PGPerson-compatible shape.
 * Source: pasted_content_2.txt (real lead data from Breeze Insurance)
 */
export const BREEZE_REAL_LEADS: PGPerson[] = [
  {
    id: 1,
    firstName: "Nick",
    lastName: "Rinauro",
    city: "Cameron Park",
    state: "CA",
    homeowner: true,
    gender: "Male",
    married: false,
    children: true,
    ageRange: "60–64",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "B",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 94,
    status: "hot",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 2,
    firstName: "Clayton",
    lastName: "Douglas",
    city: "Lodi",
    state: "CA",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "65–69",
    incomeRange: "$90K–130K",
    netWorth: "$280K–550K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 64,
    engagementScore: 72,
    status: "reached",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 3,
    firstName: "Ronald",
    lastName: "Huffman",
    city: "Waipahu",
    state: "HI",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "60–64",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 93,
    status: "hot",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 4,
    firstName: "Milvell",
    lastName: "Wilson",
    city: "Missouri City",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: false,
    children: false,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "B",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 70,
    engagementScore: 75,
    status: "warm",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 5,
    firstName: "Daniel",
    lastName: "Adams",
    city: "Richmond",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "70+",
    incomeRange: "$90K–130K",
    netWorth: "$280K–550K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 78,
    engagementScore: 79,
    status: "warm",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 6,
    firstName: "Lorena",
    lastName: "Bell",
    city: "Bay City",
    state: "MI",
    homeowner: true,
    gender: "Female",
    married: true,
    children: false,
    ageRange: "60–64",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 94,
    status: "hot",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 7,
    firstName: "Christopher",
    lastName: "Catoggio",
    city: "Sarasota",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: false,
    children: true,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 76,
    engagementScore: 78,
    status: "warm",
    productInterest: "Disability Income — Guardian Comparison",
  },
  {
    id: 8,
    firstName: "Jonathan",
    lastName: "Forman",
    city: "Sarasota",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 99,
    status: "hot",
    productInterest: "Disability Income — Ethos Comparison",
  },
  {
    id: 9,
    firstName: "Raymond",
    lastName: "Bonilla",
    city: "Lauderhill",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "60–64",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 90,
    engagementScore: 85,
    status: "warm",
    productInterest: "Disability Income — Independent Research",
  },
  {
    id: 10,
    firstName: "Joseph",
    lastName: "Czop LaBritz",
    city: "Burbank",
    state: "CA",
    homeowner: true,
    gender: "Male",
    married: false,
    children: false,
    ageRange: "65–69",
    incomeRange: "$90K–130K",
    netWorth: "$280K–550K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 91,
    status: "hot",
    productInterest: "Income Protection — Outside Application",
  },
  {
    id: 11,
    firstName: "Brian",
    lastName: "Kern Musa",
    city: "Pensacola",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 68,
    engagementScore: 74,
    status: "reached",
    productInterest: "Disability Income — Guardian Comparison",
  },
  {
    id: 12,
    firstName: "Evelyn",
    lastName: "Esquivel",
    city: "LaBelle",
    state: "FL",
    homeowner: true,
    gender: "Female",
    married: true,
    children: false,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 92,
    engagementScore: 86,
    status: "warm",
    productInterest: "Disability Income — Ethos Comparison",
  },
  {
    id: 13,
    firstName: "Michael",
    lastName: "Zaronias",
    city: "Coral Springs",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: false,
    children: true,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 62,
    engagementScore: 71,
    status: "reached",
    productInterest: "Disability Income — Independent Research",
  },
  {
    id: 14,
    firstName: "Maria",
    lastName: "Smith",
    city: "Lauderhill",
    state: "FL",
    homeowner: true,
    gender: "Female",
    married: true,
    children: false,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 72,
    engagementScore: 76,
    status: "warm",
    productInterest: "Income Protection — Outside Application",
  },
  {
    id: 15,
    firstName: "Jody",
    lastName: "Seabolt",
    city: "San Antonio",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 98,
    status: "hot",
    productInterest: "Disability Income — Ethos Comparison",
  },
  {
    id: 16,
    firstName: "Terri",
    lastName: "Leone",
    city: "Stoughton",
    state: "MA",
    homeowner: true,
    gender: "Female",
    married: false,
    children: false,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "B",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 66,
    engagementScore: 73,
    status: "reached",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 17,
    firstName: "Christine",
    lastName: "Hawk",
    city: "Ewa Beach",
    state: "HI",
    homeowner: true,
    gender: "Female",
    married: true,
    children: true,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 91,
    status: "hot",
    productInterest: "Disability Income — Guardian Comparison",
  },
  {
    id: 18,
    firstName: "Melanie",
    lastName: "Inere-Hanohano",
    city: "Waianae",
    state: "HI",
    homeowner: true,
    gender: "Female",
    married: true,
    children: false,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 62,
    engagementScore: 71,
    status: "reached",
    productInterest: "Disability Income — Independent Research",
  },
  {
    id: 19,
    firstName: "JoAnn",
    lastName: "Jones Henderson",
    city: "Deltona",
    state: "FL",
    homeowner: true,
    gender: "Female",
    married: false,
    children: true,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 74,
    engagementScore: 77,
    status: "warm",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 20,
    firstName: "Malyssa",
    lastName: "Tafoya",
    city: "Grand Terrace",
    state: "CA",
    homeowner: true,
    gender: "Female",
    married: true,
    children: false,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 92,
    status: "hot",
    productInterest: "Disability Income — Ethos Comparison",
  },
  {
    id: 21,
    firstName: "Austin",
    lastName: "Thornton",
    city: "Whitehouse",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "30–34",
    incomeRange: "$65K–90K",
    netWorth: "$40K–120K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 93,
    status: "hot",
    productInterest: "Disability Income — Independent Research",
  },
  {
    id: 22,
    firstName: "Alejandro",
    lastName: "Vasquez",
    city: "San Antonio",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: false,
    children: false,
    ageRange: "40–44",
    incomeRange: "$85K–120K",
    netWorth: "$120K–280K",
    creditRating: "B",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 96,
    engagementScore: 88,
    status: "warm",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 23,
    firstName: "Mario",
    lastName: "Barron",
    city: "Portage",
    state: "MI",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 90,
    engagementScore: 85,
    status: "warm",
    productInterest: "Disability Income — Guardian Comparison",
  },
  {
    id: 24,
    firstName: "Francis",
    lastName: "Neeb",
    city: "Keego Harbor",
    state: "MI",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 93,
    status: "hot",
    productInterest: "Disability Income — Ethos Comparison",
  },
  {
    id: 25,
    firstName: "Jonathon",
    lastName: "Witherspoon",
    city: "Sarasota",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: false,
    children: true,
    ageRange: "55–59",
    incomeRange: "$110K–160K",
    netWorth: "$350K–700K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 90,
    status: "hot",
    productInterest: "Disability Income — Independent Research",
  },
  {
    id: 26,
    firstName: "James",
    lastName: "Dunn",
    city: "Longwood",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "B",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 96,
    engagementScore: 88,
    status: "warm",
    productInterest: "Income Protection — Outside Application",
  },
  {
    id: 27,
    firstName: "Douglas",
    lastName: "Lynch",
    city: "Orlando",
    state: "FL",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "B",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 66,
    engagementScore: 73,
    status: "reached",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 28,
    firstName: "Katrillany",
    lastName: "Williams",
    city: "Apopka",
    state: "FL",
    homeowner: true,
    gender: "Female",
    married: false,
    children: false,
    ageRange: "50–54",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 94,
    engagementScore: 87,
    status: "warm",
    productInterest: "Disability Income — Guardian Comparison",
  },
  {
    id: 29,
    firstName: "Shezetta",
    lastName: "Powell",
    city: "Lehigh Acres",
    state: "FL",
    homeowner: true,
    gender: "Female",
    married: true,
    children: true,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 96,
    status: "hot",
    productInterest: "Disability Income — Ethos Comparison",
  },
  {
    id: 30,
    firstName: "Jamey",
    lastName: "Jutson",
    city: "West Bloomfield",
    state: "MI",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 76,
    engagementScore: 78,
    status: "warm",
    productInterest: "Disability Income — Independent Research",
  },
  {
    id: 31,
    firstName: "Jeremy",
    lastName: "Zoito",
    city: "Worcester",
    state: "MA",
    homeowner: true,
    gender: "Male",
    married: false,
    children: true,
    ageRange: "50–54",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 66,
    engagementScore: 73,
    status: "reached",
    productInterest: "Income Protection — Outside Application",
  },
  {
    id: 32,
    firstName: "Keoni",
    lastName: "Makaweo",
    city: "Waianae",
    state: "HI",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "40–44",
    incomeRange: "$85K–120K",
    netWorth: "$120K–280K",
    creditRating: "B",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 93,
    status: "hot",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 33,
    firstName: "Shauna",
    lastName: "Mundorf",
    city: "Milford",
    state: "MA",
    homeowner: true,
    gender: "Female",
    married: true,
    children: true,
    ageRange: "30–34",
    incomeRange: "$65K–90K",
    netWorth: "$40K–120K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 68,
    engagementScore: 74,
    status: "reached",
    productInterest: "Disability Income — Guardian Comparison",
  },
  {
    id: 34,
    firstName: "Lanforth",
    lastName: "Lee Sr.",
    city: "Austin",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: false,
    children: false,
    ageRange: "50–54",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 89,
    status: "warm",
    productInterest: "Income Protection — Outside Application",
  },
  {
    id: 35,
    firstName: "Scott",
    lastName: "Perry",
    city: "Montgomery",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "45–49",
    incomeRange: "$100K–150K",
    netWorth: "$200K–450K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 89,
    status: "warm",
    productInterest: "Disability Income — Ethos Comparison",
  },
  {
    id: 36,
    firstName: "Samir",
    lastName: "Barash",
    city: "Oak Park",
    state: "MI",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "65–69",
    incomeRange: "$90K–130K",
    netWorth: "$280K–550K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 78,
    engagementScore: 79,
    status: "warm",
    productInterest: "Disability Income — Independent Research",
  },
  {
    id: 37,
    firstName: "Austin",
    lastName: "Beamish",
    city: "Owosso",
    state: "MI",
    homeowner: true,
    gender: "Male",
    married: false,
    children: true,
    ageRange: "25–29",
    incomeRange: "$65K–90K",
    netWorth: "$40K–120K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 76,
    engagementScore: 78,
    status: "warm",
    productInterest: "Income Protection — Multi-Carrier",
  },
  {
    id: 38,
    firstName: "David",
    lastName: "Graeff",
    city: "Austin",
    state: "TX",
    homeowner: true,
    gender: "Male",
    married: true,
    children: false,
    ageRange: "40–44",
    incomeRange: "$85K–120K",
    netWorth: "$120K–280K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 98,
    engagementScore: 94,
    status: "hot",
    productInterest: "Disability Income — Guardian Comparison",
  },
  {
    id: 39,
    firstName: "Riley",
    lastName: "Howsden",
    city: "Los Angeles",
    state: "CA",
    homeowner: true,
    gender: "Male",
    married: true,
    children: true,
    ageRange: "35–39",
    incomeRange: "$85K–120K",
    netWorth: "$120K–280K",
    creditRating: "A",
    hasPhone: true,
    hasEmail: true,
    adsSeen: 3,
    completionRate: 78,
    engagementScore: 79,
    status: "warm",
    productInterest: "Income Protection — Outside Application",
  }
];

export const BREEZE_REAL_LEADS_STATS = {
  totalList: 39,
  homeowners: 39,
  withEmail: 39,
  validEmails: 39,
  goldEmails: 39,
  validPct: 100,
  withPhone: 39,
  linkedinReachable: 28,
  targetUniverse: 39,
  avgIncomeLabel: "$85K–$140K",
  netWorthLabel: "$200K–$500K",
  creditGrade: "B+",
};
