// Breeze Insurance People Segment — VALID GOLD email list
// Working professionals, disability insurance buyers, Meta/Google/LinkedIn/Email targeting

export interface BreezePerson {
  id: string;
  firstName: string;
  lastName: string;
  city: string;
  state: string;
  zip: string;
  email: string;
  emailProvider: string;
  adsSeen: number;
  completionRate: number;
  productInterest: string;
  status: "hot" | "warm" | "reached" | "pending";
  channel: string;
  ageRange: string;
  incomeRange: string;
}

export const BREEZE_SEGMENT_STATS = {
  totalList: 5913,
  homeowners: 3841,
  withEmail: 5285,
  validEmails: 5285,
  goldEmails: 439,
  validPct: 89.38,
  withPhone: 4120,
  linkedinReachable: 2840,
  targetUniverse: 5913,
};

export const BREEZE_PEOPLE: BreezePerson[] = [
  { id: "b1", firstName: "Cono", lastName: "Namorato", city: "Arlington", state: "VA", zip: "22236", email: "cr***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 91, productInterest: "Short-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$90K–$130K" },
  { id: "b2", firstName: "Barry", lastName: "Stein", city: "Miami", state: "FL", zip: "33101", email: "ba***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 85, productInterest: "Long-Term Disability", status: "warm", channel: "Meta", ageRange: "45–54", incomeRange: "$100K–$150K" },
  { id: "b3", firstName: "Brett", lastName: "Sova", city: "Lexington", state: "KY", zip: "40502", email: "so***@gmail.com", emailProvider: "Gmail", adsSeen: 4, completionRate: 80, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "30–39", incomeRange: "$70K–$100K" },
  { id: "b4", firstName: "Bryce", lastName: "Erickson", city: "Dallas", state: "TX", zip: "75201", email: "br***@yahoo.com", emailProvider: "Yahoo", adsSeen: 6, completionRate: 88, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$95K–$140K" },
  { id: "b5", firstName: "Brian", lastName: "Grogan", city: "Chicago", state: "IL", zip: "60624", email: "gr***@gmail.com", emailProvider: "Gmail", adsSeen: 8, completionRate: 93, productInterest: "Short-Term Disability", status: "hot", channel: "Email", ageRange: "40–49", incomeRange: "$85K–$120K" },
  { id: "b6", firstName: "Alexander", lastName: "Dorsky", city: "Miami", state: "FL", zip: "33101", email: "th***@yahoo.com", emailProvider: "Yahoo", adsSeen: 5, completionRate: 84, productInterest: "Long-Term Disability", status: "warm", channel: "Meta", ageRange: "45–54", incomeRange: "$110K–$160K" },
  { id: "b7", firstName: "Connie", lastName: "Roden", city: "Spokane", state: "WA", zip: "99201", email: "co***@yahoo.com", emailProvider: "Yahoo", adsSeen: 4, completionRate: 79, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "35–44", incomeRange: "$70K–$100K" },
  { id: "b8", firstName: "Jennifer", lastName: "Schomburg", city: "Tacoma", state: "WA", zip: "98434", email: "je***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 89, productInterest: "Long-Term Disability", status: "warm", channel: "Google", ageRange: "30–39", incomeRange: "$75K–$110K" },
  { id: "b9", firstName: "Anil", lastName: "Kalra", city: "West Chicago", state: "IL", zip: "60185", email: "ka***@yahoo.com", emailProvider: "Yahoo", adsSeen: 7, completionRate: 92, productInterest: "Short-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "40–49", incomeRange: "$100K–$150K" },
  { id: "b10", firstName: "Boris", lastName: "Pinzon", city: "Miami", state: "FL", zip: "33101", email: "yv***@hotmail.com", emailProvider: "Hotmail", adsSeen: 3, completionRate: 74, productInterest: "Long-Term Disability", status: "reached", channel: "Meta", ageRange: "45–54", incomeRange: "$80K–$120K" },
  { id: "b11", firstName: "Bryan", lastName: "Waites", city: "Duluth", state: "GA", zip: "30096", email: "wa***@hotmail.com", emailProvider: "Hotmail", adsSeen: 5, completionRate: 83, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "35–44", incomeRange: "$85K–$120K" },
  { id: "b12", firstName: "David", lastName: "Thomsen", city: "Crystal Lake", state: "IL", zip: "60014", email: "mo***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 87, productInterest: "Long-Term Disability", status: "warm", channel: "Google", ageRange: "40–49", incomeRange: "$90K–$130K" },
  { id: "b13", firstName: "Harry", lastName: "Aldrich", city: "Miami", state: "FL", zip: "33101", email: "xo***@hotmail.com", emailProvider: "Hotmail", adsSeen: 4, completionRate: 78, productInterest: "Short-Term Disability", status: "reached", channel: "Meta", ageRange: "50–59", incomeRange: "$75K–$110K" },
  { id: "b14", firstName: "Jenny", lastName: "Kissinger", city: "Ashland", state: "NE", zip: "68003", email: "jk***@windstream.net", emailProvider: "Other", adsSeen: 5, completionRate: 82, productInterest: "Long-Term Disability", status: "warm", channel: "Email", ageRange: "35–44", incomeRange: "$70K–$100K" },
  { id: "b15", firstName: "Melody", lastName: "Dugger", city: "Phoenix", state: "AZ", zip: "85001", email: "md***@yahoo.com", emailProvider: "Yahoo", adsSeen: 6, completionRate: 88, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "30–39", incomeRange: "$75K–$110K" },
  { id: "b16", firstName: "Nancy", lastName: "Robie", city: "Springboro", state: "OH", zip: "45066", email: "na***@outlook.com", emailProvider: "Outlook", adsSeen: 7, completionRate: 91, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "40–49", incomeRange: "$90K–$130K" },
  { id: "b17", firstName: "Shaun", lastName: "Coyle", city: "Park Ridge", state: "IL", zip: "60068", email: "br***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 85, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "35–44", incomeRange: "$80K–$120K" },
  { id: "b18", firstName: "Thomas", lastName: "Kiely", city: "Iowa City", state: "IA", zip: "52240", email: "ki***@mchsi.com", emailProvider: "Other", adsSeen: 4, completionRate: 79, productInterest: "Long-Term Disability", status: "warm", channel: "Google", ageRange: "45–54", incomeRange: "$85K–$120K" },
  { id: "b19", firstName: "Kang", lastName: "Shin", city: "Denver", state: "CO", zip: "80263", email: "kg***@gmail.com", emailProvider: "Gmail", adsSeen: 8, completionRate: 94, productInterest: "Short-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$100K–$150K" },
  { id: "b20", firstName: "Terry", lastName: "Corey", city: "Arvada", state: "CO", zip: "80226", email: "co***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 84, productInterest: "Long-Term Disability", status: "warm", channel: "Meta", ageRange: "40–49", incomeRange: "$80K–$120K" },
  { id: "b21", firstName: "Krystle", lastName: "Seaver", city: "Las Vegas", state: "NV", zip: "89150", email: "kr***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 87, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "30–39", incomeRange: "$70K–$100K" },
  { id: "b22", firstName: "Justin", lastName: "Warner", city: "Columbus", state: "OH", zip: "43211", email: "ju***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 91, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$90K–$130K" },
  { id: "b23", firstName: "David", lastName: "Fleming", city: "Cordova", state: "TN", zip: "38023", email: "dm***@hotmail.com", emailProvider: "Hotmail", adsSeen: 4, completionRate: 80, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "40–49", incomeRange: "$80K–$120K" },
  { id: "b24", firstName: "Keith", lastName: "Nicolet", city: "Johnston", state: "IA", zip: "50187", email: "kn***@yahoo.com", emailProvider: "Yahoo", adsSeen: 5, completionRate: 83, productInterest: "Long-Term Disability", status: "warm", channel: "Email", ageRange: "45–54", incomeRange: "$85K–$120K" },
  { id: "b25", firstName: "Elena", lastName: "Echevarria", city: "Miami", state: "FL", zip: "33130", email: "ta***@msn.com", emailProvider: "MSN", adsSeen: 6, completionRate: 88, productInterest: "Short-Term Disability", status: "warm", channel: "Meta", ageRange: "35–44", incomeRange: "$75K–$110K" },
  { id: "b26", firstName: "Barbara", lastName: "Adornetto", city: "Morrisville", state: "NC", zip: "27560", email: "ad***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 92, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "40–49", incomeRange: "$90K–$130K" },
  { id: "b27", firstName: "Jayson", lastName: "Dammen", city: "Scottsdale", state: "AZ", zip: "85263", email: "jc***@gmail.com", emailProvider: "Gmail", adsSeen: 8, completionRate: 94, productInterest: "Short-Term Disability", status: "hot", channel: "Google", ageRange: "35–44", incomeRange: "$100K–$150K" },
  { id: "b28", firstName: "Kevin", lastName: "Sido", city: "Chicago", state: "IL", zip: "60620", email: "je***@yahoo.com", emailProvider: "Yahoo", adsSeen: 4, completionRate: 78, productInterest: "Long-Term Disability", status: "reached", channel: "Email", ageRange: "45–54", incomeRange: "$75K–$110K" },
  { id: "b29", firstName: "Kevin", lastName: "Dolhay", city: "Lawrence", state: "MI", zip: "49093", email: "kd***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 84, productInterest: "Short-Term Disability", status: "warm", channel: "Meta", ageRange: "40–49", incomeRange: "$80K–$120K" },
  { id: "b30", firstName: "Judson", lastName: "Just", city: "Denver", state: "CO", zip: "80134", email: "ju***@yahoo.com", emailProvider: "Yahoo", adsSeen: 6, completionRate: 87, productInterest: "Long-Term Disability", status: "warm", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$85K–$120K" },
  { id: "b31", firstName: "Kyle", lastName: "Lansberry", city: "Indianapolis", state: "IN", zip: "46210", email: "pr***@yahoo.com", emailProvider: "Yahoo", adsSeen: 5, completionRate: 83, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "30–39", incomeRange: "$70K–$100K" },
  { id: "b32", firstName: "Brett", lastName: "Briggs", city: "Charlotte", state: "NC", zip: "28279", email: "bd***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 91, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$95K–$140K" },
  { id: "b33", firstName: "Elizabeth", lastName: "Gabb", city: "Pompano Beach", state: "FL", zip: "33033", email: "em***@yahoo.com", emailProvider: "Yahoo", adsSeen: 4, completionRate: 79, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "40–49", incomeRange: "$75K–$110K" },
  { id: "b34", firstName: "Janetta", lastName: "Shanklin", city: "Franklin", state: "KY", zip: "42176", email: "js***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 84, productInterest: "Long-Term Disability", status: "warm", channel: "Meta", ageRange: "35–44", incomeRange: "$70K–$100K" },
  { id: "b35", firstName: "Amy", lastName: "Hasbargen", city: "Minneapolis", state: "MN", zip: "55440", email: "ah***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 88, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "30–39", incomeRange: "$75K–$110K" },
  { id: "b36", firstName: "Karen", lastName: "Clupper", city: "Lancaster", state: "PA", zip: "19312", email: "kd***@hotmail.com", emailProvider: "Hotmail", adsSeen: 7, completionRate: 91, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "45–54", incomeRange: "$90K–$130K" },
  { id: "b37", firstName: "Christina", lastName: "Catera", city: "Clinton Township", state: "MI", zip: "48036", email: "cm***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 85, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "35–44", incomeRange: "$80K–$120K" },
  { id: "b38", firstName: "Alexandra", lastName: "Cross", city: "Nashville", state: "TN", zip: "37210", email: "al***@gmail.com", emailProvider: "Gmail", adsSeen: 8, completionRate: 93, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "30–39", incomeRange: "$90K–$130K" },
  { id: "b39", firstName: "Karl", lastName: "Robinson", city: "Minneapolis", state: "MN", zip: "55418", email: "el***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 88, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "40–49", incomeRange: "$85K–$120K" },
  { id: "b40", firstName: "Jonathan", lastName: "Starr", city: "San Antonio", state: "TX", zip: "78216", email: "js***@aol.com", emailProvider: "AOL", adsSeen: 5, completionRate: 82, productInterest: "Long-Term Disability", status: "warm", channel: "Meta", ageRange: "45–54", incomeRange: "$80K–$120K" },
  { id: "b41", firstName: "Aarthie", lastName: "Ramachandran", city: "Charlotte", state: "NC", zip: "28234", email: "aa***@yahoo.com", emailProvider: "Yahoo", adsSeen: 7, completionRate: 91, productInterest: "Short-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$100K–$150K" },
  { id: "b42", firstName: "Frank", lastName: "Kroll", city: "Arlington", state: "VA", zip: "22201", email: "ka***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 89, productInterest: "Long-Term Disability", status: "warm", channel: "Email", ageRange: "40–49", incomeRange: "$95K–$140K" },
  { id: "b43", firstName: "Kevin", lastName: "Scott", city: "Coraopolis", state: "PA", zip: "15108", email: "vy***@gmail.com", emailProvider: "Gmail", adsSeen: 4, completionRate: 78, productInterest: "Short-Term Disability", status: "reached", channel: "Google", ageRange: "35–44", incomeRange: "$75K–$110K" },
  { id: "b44", firstName: "Michelle", lastName: "Hartley", city: "Atlanta", state: "GA", zip: "30301", email: "mh***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 92, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$95K–$140K" },
  { id: "b45", firstName: "Daniel", lastName: "Ostrowski", city: "Houston", state: "TX", zip: "77001", email: "do***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 88, productInterest: "Short-Term Disability", status: "warm", channel: "Meta", ageRange: "40–49", incomeRange: "$85K–$120K" },
  { id: "b46", firstName: "Sarah", lastName: "Whitmore", city: "Seattle", state: "WA", zip: "98101", email: "sw***@gmail.com", emailProvider: "Gmail", adsSeen: 8, completionRate: 94, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "30–39", incomeRange: "$100K–$150K" },
  { id: "b47", firstName: "Marcus", lastName: "Webb", city: "Phoenix", state: "AZ", zip: "85001", email: "mw***@yahoo.com", emailProvider: "Yahoo", adsSeen: 5, completionRate: 83, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "35–44", incomeRange: "$80K–$120K" },
  { id: "b48", firstName: "Lisa", lastName: "Nguyen", city: "San Jose", state: "CA", zip: "95101", email: "ln***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 91, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$110K–$160K" },
  { id: "b49", firstName: "Robert", lastName: "Chambers", city: "Baltimore", state: "MD", zip: "21201", email: "rc***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 84, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "40–49", incomeRange: "$85K–$120K" },
  { id: "b50", firstName: "Patricia", lastName: "Morales", city: "San Diego", state: "CA", zip: "92101", email: "pm***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 88, productInterest: "Long-Term Disability", status: "warm", channel: "Meta", ageRange: "35–44", incomeRange: "$90K–$130K" },
  { id: "b51", firstName: "James", lastName: "Kowalski", city: "Milwaukee", state: "WI", zip: "53201", email: "jk***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 92, productInterest: "Short-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "40–49", incomeRange: "$90K–$130K" },
  { id: "b52", firstName: "Angela", lastName: "Fontaine", city: "New Orleans", state: "LA", zip: "70112", email: "af***@gmail.com", emailProvider: "Gmail", adsSeen: 4, completionRate: 79, productInterest: "Long-Term Disability", status: "warm", channel: "Google", ageRange: "35–44", incomeRange: "$75K–$110K" },
  { id: "b53", firstName: "Christopher", lastName: "Delgado", city: "El Paso", state: "TX", zip: "79901", email: "cd***@yahoo.com", emailProvider: "Yahoo", adsSeen: 5, completionRate: 83, productInterest: "Short-Term Disability", status: "warm", channel: "Email", ageRange: "30–39", incomeRange: "$70K–$100K" },
  { id: "b54", firstName: "Sandra", lastName: "Bergstrom", city: "Portland", state: "OR", zip: "97201", email: "sb***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 87, productInterest: "Long-Term Disability", status: "warm", channel: "LinkedIn", ageRange: "40–49", incomeRange: "$85K–$120K" },
  { id: "b55", firstName: "William", lastName: "Nakamura", city: "Bellevue", state: "WA", zip: "98004", email: "wn***@gmail.com", emailProvider: "Gmail", adsSeen: 8, completionRate: 95, productInterest: "Short-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$120K–$180K" },
  { id: "b56", firstName: "Dorothy", lastName: "Ashford", city: "Raleigh", state: "NC", zip: "27601", email: "da***@gmail.com", emailProvider: "Gmail", adsSeen: 5, completionRate: 84, productInterest: "Long-Term Disability", status: "warm", channel: "Meta", ageRange: "45–54", incomeRange: "$80K–$120K" },
  { id: "b57", firstName: "Harold", lastName: "Kimura", city: "Honolulu", state: "HI", zip: "96801", email: "hk***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 88, productInterest: "Short-Term Disability", status: "warm", channel: "Google", ageRange: "40–49", incomeRange: "$90K–$130K" },
  { id: "b58", firstName: "Catherine", lastName: "Morse", city: "Boston", state: "MA", zip: "02101", email: "cm***@gmail.com", emailProvider: "Gmail", adsSeen: 7, completionRate: 91, productInterest: "Long-Term Disability", status: "hot", channel: "LinkedIn", ageRange: "35–44", incomeRange: "$100K–$150K" },
  { id: "b59", firstName: "Raymond", lastName: "Osei", city: "Columbus", state: "OH", zip: "43201", email: "ro***@yahoo.com", emailProvider: "Yahoo", adsSeen: 4, completionRate: 78, productInterest: "Short-Term Disability", status: "reached", channel: "Email", ageRange: "40–49", incomeRange: "$75K–$110K" },
  { id: "b60", firstName: "Vivienne", lastName: "Larsson", city: "Salt Lake City", state: "UT", zip: "84101", email: "vl***@gmail.com", emailProvider: "Gmail", adsSeen: 6, completionRate: 88, productInterest: "Long-Term Disability", status: "warm", channel: "LinkedIn", ageRange: "30–39", incomeRange: "$85K–$120K" },
];
