// Exact Audience — Campaign Client Registry
// 35 active campaigns. IDs 1, 2, 3, 4 have full dashboards. Rest are active placeholders.

export type ClientStatus = "active" | "paused" | "pending";

export interface CampaignClient {
  id: number;
  slug: string;                // URL slug for routing
  name: string;
  vertical: string;
  location: string;
  description: string;
  domain: string;
  campaign: string;
  budget: string;
  startDate: string;
  status: ClientStatus;
  hasDashboard: boolean;       // true = full dashboard; false = placeholder
  // Spark data — 14-day impression trend for card preview
  trend: number[];
  impressionsToDate: number;
  reachToDate: number;
  completionRate: number;
  primaryColor: string;        // brand accent for card
}

// Helper: generate a rising trend array with slight variance
function risingTrend(base: number, days = 14): number[] {
  const arr: number[] = [];
  let val = base;
  for (let i = 0; i < days; i++) {
    val = Math.round(val * (1 + (Math.random() * 0.06 + 0.01)));
    arr.push(val);
  }
  return arr;
}

export const CLIENTS: CampaignClient[] = [
  // ── FULL DASHBOARDS ──────────────────────────────────────────────────────────
  {
    id: 1,
    slug: "land-rover-north-scottsdale",
    name: "Land Rover North Scottsdale",
    vertical: "Luxury Automotive",
    location: "Scottsdale, AZ",
    description: "Defender Conquest campaign targeting luxury SUV intenders",
    domain: "landrovernorthscottsdale.com",
    campaign: "Defender Conquest 2026",
    budget: "$97,500",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: true,
    trend: risingTrend(48000),
    impressionsToDate: 4871342,
    reachToDate: 188640,
    completionRate: 87.5,
    primaryColor: "#1a6b3c",
  },
  {
    id: 2,
    slug: "lamborghini-scottsdale",
    name: "Lamborghini of Scottsdale",
    vertical: "Ultra-Luxury Automotive",
    location: "Scottsdale, AZ",
    description: "Conquest campaign for Urus & Huracán ultra-luxury buyers",
    domain: "lamborghiniofscottsdale.com",
    campaign: "Urus Conquest 2026",
    budget: "$112,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: true,
    trend: risingTrend(52000),
    impressionsToDate: 5214800,
    reachToDate: 201340,
    completionRate: 89.2,
    primaryColor: "#d4a017",
  },
  {
    id: 3,
    slug: "warby-parker",
    name: "Warby Parker",
    vertical: "Eyewear & Retail",
    location: "New York, NY",
    description: "National brand awareness and try-at-home conversion campaign",
    domain: "warbyparker.com",
    campaign: "Spring Vision 2026",
    budget: "$84,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: true,
    trend: risingTrend(44000),
    impressionsToDate: 4428700,
    reachToDate: 174200,
    completionRate: 85.8,
    primaryColor: "#1d4ed8",
  },
  {
    id: 4,
    slug: "policygenius",
    name: "PolicyGenius",
    vertical: "Insurance Tech",
    location: "New York, NY",
    description: "Life & home insurance comparison platform acquisition campaign",
    domain: "policygenius.com",
    campaign: "Life Insurance Awareness 2026",
    budget: "$78,500",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: true,
    trend: risingTrend(38000),
    impressionsToDate: 3987200,
    reachToDate: 162400,
    completionRate: 83.4,
    primaryColor: "#7c3aed",
  },

  // ── ACTIVE PLACEHOLDERS ───────────────────────────────────────────────────────
  {
    id: 5,
    slug: "black-rifle-coffee",
    name: "Black Rifle Coffee Company",
    vertical: "Coffee & Lifestyle",
    location: "Salt Lake City, UT",
    description: "Veteran-owned premium coffee brand loyalty & acquisition",
    domain: "blackriflecoffee.com",
    campaign: "Mission Roast 2026",
    budget: "$62,000",
    startDate: "May 8, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(31000),
    impressionsToDate: 2841200,
    reachToDate: 118400,
    completionRate: 84.1,
    primaryColor: "#374151",
  },
  {
    id: 6,
    slug: "aura-frames",
    name: "Aura Frames",
    vertical: "Consumer Electronics",
    location: "San Francisco, CA",
    description: "Smart digital photo frame gifting season campaign",
    domain: "auraframes.com",
    campaign: "Gift Season 2026",
    budget: "$48,000",
    startDate: "May 8, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(24000),
    impressionsToDate: 2214800,
    reachToDate: 94200,
    completionRate: 82.7,
    primaryColor: "#0ea5e9",
  },
  {
    id: 7,
    slug: "oura-ring",
    name: "Oura Ring",
    vertical: "Health & Wearables",
    location: "San Francisco, CA",
    description: "Health-tracking smart ring awareness and direct-to-consumer",
    domain: "ouraring.com",
    campaign: "Health Intelligence 2026",
    budget: "$71,000",
    startDate: "May 5, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(36000),
    impressionsToDate: 3412600,
    reachToDate: 141800,
    completionRate: 86.3,
    primaryColor: "#6366f1",
  },
  {
    id: 8,
    slug: "sonic-drive-in",
    name: "Sonic Drive-In",
    vertical: "Quick Service Restaurant",
    location: "Oklahoma City, OK",
    description: "Happy hour promotion and new menu item awareness",
    domain: "sonicdrivein.com",
    campaign: "Summer Sips 2026",
    budget: "$55,000",
    startDate: "May 12, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(28000),
    impressionsToDate: 2687400,
    reachToDate: 112600,
    completionRate: 81.9,
    primaryColor: "#f97316",
  },
  {
    id: 9,
    slug: "rafi-law-group",
    name: "Rafi Law Group",
    vertical: "Personal Injury Law",
    location: "Atlanta, GA",
    description: "Personal injury attorney brand awareness and lead generation",
    domain: "rafilawgroup.com",
    campaign: "Justice for You 2026",
    budget: "$68,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(34000),
    impressionsToDate: 3187200,
    reachToDate: 128400,
    completionRate: 85.2,
    primaryColor: "#dc2626",
  },
  {
    id: 10,
    slug: "morgan-morgan",
    name: "Morgan & Morgan",
    vertical: "Personal Injury Law",
    location: "Orlando, FL",
    description: "National personal injury law firm mass tort acquisition",
    domain: "morganandmorgan.com",
    campaign: "For the People 2026",
    budget: "$142,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(72000),
    impressionsToDate: 6841200,
    reachToDate: 274800,
    completionRate: 88.4,
    primaryColor: "#b91c1c",
  },
  {
    id: 11,
    slug: "phoenix-mercury",
    name: "Phoenix Mercury",
    vertical: "Professional Sports",
    location: "Phoenix, AZ",
    description: "WNBA season ticket sales and fan acquisition campaign",
    domain: "wnba.com/mercury",
    campaign: "Mercury Rising 2026",
    budget: "$44,000",
    startDate: "May 15, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(22000),
    impressionsToDate: 2014800,
    reachToDate: 84200,
    completionRate: 80.6,
    primaryColor: "#f59e0b",
  },
  {
    id: 12,
    slug: "phoenix-suns",
    name: "Phoenix Suns",
    vertical: "Professional Sports",
    location: "Phoenix, AZ",
    description: "NBA season ticket renewals and premium seating campaign",
    domain: "suns.com",
    campaign: "Valley of the Sun 2026",
    budget: "$88,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(44000),
    impressionsToDate: 4214800,
    reachToDate: 168400,
    completionRate: 87.1,
    primaryColor: "#e35205",
  },
  {
    id: 13,
    slug: "marcos-pizza",
    name: "Marco's Pizza",
    vertical: "Quick Service Restaurant",
    location: "Toledo, OH",
    description: "Franchise awareness and online ordering conversion campaign",
    domain: "marcos.com",
    campaign: "Fresh Crust 2026",
    budget: "$52,000",
    startDate: "May 8, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(26000),
    impressionsToDate: 2487200,
    reachToDate: 104800,
    completionRate: 82.3,
    primaryColor: "#16a34a",
  },
  {
    id: 14,
    slug: "dp-electric",
    name: "DP Electric",
    vertical: "Electrical Contractor",
    location: "Tempe, AZ",
    description: "Commercial & residential electrical services lead generation",
    domain: "dpelectric.com",
    campaign: "Power Up Arizona 2026",
    budget: "$38,000",
    startDate: "May 12, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(19000),
    impressionsToDate: 1787200,
    reachToDate: 74800,
    completionRate: 79.8,
    primaryColor: "#eab308",
  },
  {
    id: 15,
    slug: "us-fleet-tracking",
    name: "US Fleet Tracking",
    vertical: "Fleet Technology",
    location: "Oklahoma City, OK",
    description: "GPS fleet tracking SaaS B2B acquisition campaign",
    domain: "usfleettracking.com",
    campaign: "Track & Grow 2026",
    budget: "$46,000",
    startDate: "May 5, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(23000),
    impressionsToDate: 2187200,
    reachToDate: 91400,
    completionRate: 83.7,
    primaryColor: "#0284c7",
  },
  {
    id: 16,
    slug: "life-success",
    name: "Life Success",
    vertical: "Personal Development",
    location: "Scottsdale, AZ",
    description: "Coaching platform and personal development program enrollment",
    domain: "lifesuccess.ai",
    campaign: "Unlock Your Potential 2026",
    budget: "$34,000",
    startDate: "May 15, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(17000),
    impressionsToDate: 1587200,
    reachToDate: 66400,
    completionRate: 78.4,
    primaryColor: "#8b5cf6",
  },
  {
    id: 17,
    slug: "dell",
    name: "Dell Technologies",
    vertical: "Technology",
    location: "Round Rock, TX",
    description: "Business laptop and workstation enterprise awareness campaign",
    domain: "dell.com",
    campaign: "Work Smarter 2026",
    budget: "$124,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(62000),
    impressionsToDate: 5987200,
    reachToDate: 241800,
    completionRate: 86.9,
    primaryColor: "#1d4ed8",
  },
  {
    id: 18,
    slug: "razr-golf",
    name: "RAZR Golf",
    vertical: "Golf & Sports",
    location: "Carlsbad, CA",
    description: "Premium golf equipment brand awareness and DTC conversion",
    domain: "razrgolf.com",
    campaign: "Fairway Edge 2026",
    budget: "$41,000",
    startDate: "May 8, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(20500),
    impressionsToDate: 1914800,
    reachToDate: 79400,
    completionRate: 81.2,
    primaryColor: "#059669",
  },
  {
    id: 19,
    slug: "butterfield-robinson",
    name: "Butterfield & Robinson",
    vertical: "Luxury Travel",
    location: "Toronto, ON",
    description: "Ultra-luxury active travel and bespoke journey acquisition",
    domain: "butterfield-robinson.com",
    campaign: "Journey Beyond 2026",
    budget: "$94,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(47000),
    impressionsToDate: 4487200,
    reachToDate: 178400,
    completionRate: 88.7,
    primaryColor: "#0f766e",
  },
  {
    id: 20,
    slug: "camping-world",
    name: "Camping World",
    vertical: "Outdoor & RV Retail",
    location: "Lincolnshire, IL",
    description: "RV and outdoor gear seasonal sales and loyalty campaign",
    domain: "campingworld.com",
    campaign: "Open Road 2026",
    budget: "$67,000",
    startDate: "May 5, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(33500),
    impressionsToDate: 3187200,
    reachToDate: 128400,
    completionRate: 83.1,
    primaryColor: "#15803d",
  },
  {
    id: 21,
    slug: "tom-ford",
    name: "Tom Ford",
    vertical: "Luxury Fashion & Beauty",
    location: "New York, NY",
    description: "Luxury fragrance and eyewear brand awareness campaign",
    domain: "tomford.com",
    campaign: "Iconic Luxury 2026",
    budget: "$108,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(54000),
    impressionsToDate: 5187200,
    reachToDate: 208400,
    completionRate: 90.1,
    primaryColor: "#1c1917",
  },
  {
    id: 22,
    slug: "mindbodygreen",
    name: "mindbodygreen",
    vertical: "Health & Wellness Media",
    location: "New York, NY",
    description: "Wellness content platform subscription and supplement sales",
    domain: "mindbodygreen.com",
    campaign: "Whole Health 2026",
    budget: "$49,000",
    startDate: "May 8, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(24500),
    impressionsToDate: 2314800,
    reachToDate: 96400,
    completionRate: 82.8,
    primaryColor: "#16a34a",
  },
  {
    id: 23,
    slug: "bulletproof-coffee",
    name: "Bulletproof Coffee",
    vertical: "Health & Nutrition",
    location: "Austin, TX",
    description: "Biohacking coffee and supplement brand DTC acquisition",
    domain: "bulletproof.com",
    campaign: "Upgrade Your Mind 2026",
    budget: "$43,000",
    startDate: "May 12, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(21500),
    impressionsToDate: 2014800,
    reachToDate: 84200,
    completionRate: 81.6,
    primaryColor: "#78350f",
  },
  {
    id: 24,
    slug: "true-shot-ammo",
    name: "True Shot Ammo",
    vertical: "Firearms & Outdoor",
    location: "Phoenix, AZ",
    description: "Online ammunition retailer brand awareness and conversion",
    domain: "trueshotammo.com",
    campaign: "Ready Aim 2026",
    budget: "$36,000",
    startDate: "May 15, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(18000),
    impressionsToDate: 1687200,
    reachToDate: 70400,
    completionRate: 80.3,
    primaryColor: "#374151",
  },
  {
    id: 25,
    slug: "vuori",
    name: "Vuori",
    vertical: "Athletic Apparel",
    location: "Encinitas, CA",
    description: "Premium performance apparel DTC and retail awareness campaign",
    domain: "vuoriclothing.com",
    campaign: "Move Forward 2026",
    budget: "$74,000",
    startDate: "May 5, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(37000),
    impressionsToDate: 3514800,
    reachToDate: 144400,
    completionRate: 85.4,
    primaryColor: "#0369a1",
  },
  {
    id: 26,
    slug: "yeti",
    name: "YETI",
    vertical: "Outdoor & Lifestyle",
    location: "Austin, TX",
    description: "Premium cooler and drinkware brand awareness and gifting",
    domain: "yeti.com",
    campaign: "Built for the Wild 2026",
    budget: "$86,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(43000),
    impressionsToDate: 4114800,
    reachToDate: 164400,
    completionRate: 86.7,
    primaryColor: "#1e40af",
  },
  {
    id: 27,
    slug: "whoop",
    name: "WHOOP",
    vertical: "Health & Wearables",
    location: "Boston, MA",
    description: "Performance fitness wearable subscription acquisition campaign",
    domain: "whoop.com",
    campaign: "Unlock Recovery 2026",
    budget: "$79,000",
    startDate: "May 5, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(39500),
    impressionsToDate: 3787200,
    reachToDate: 154400,
    completionRate: 86.1,
    primaryColor: "#111827",
  },
  {
    id: 28,
    slug: "webflow",
    name: "Webflow",
    vertical: "SaaS / No-Code",
    location: "San Francisco, CA",
    description: "Visual web development platform B2B and prosumer acquisition",
    domain: "webflow.com",
    campaign: "Build Without Limits 2026",
    budget: "$92,000",
    startDate: "May 1, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(46000),
    impressionsToDate: 4414800,
    reachToDate: 178400,
    completionRate: 87.3,
    primaryColor: "#4f46e5",
  },
  {
    id: 29,
    slug: "california-pizza-kitchen",
    name: "California Pizza Kitchen",
    vertical: "Casual Dining",
    location: "Los Angeles, CA",
    description: "Restaurant brand awareness and loyalty program enrollment",
    domain: "cpk.com",
    campaign: "Crave More 2026",
    budget: "$58,000",
    startDate: "May 8, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(29000),
    impressionsToDate: 2787200,
    reachToDate: 114400,
    completionRate: 82.6,
    primaryColor: "#dc2626",
  },
  {
    id: 30,
    slug: "portland-gear",
    name: "Portland Gear",
    vertical: "Lifestyle Apparel",
    location: "Portland, OR",
    description: "City-pride apparel brand awareness and e-commerce conversion",
    domain: "portlandgear.com",
    campaign: "Keep It PDX 2026",
    budget: "$31,000",
    startDate: "May 15, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(15500),
    impressionsToDate: 1487200,
    reachToDate: 62400,
    completionRate: 79.2,
    primaryColor: "#7c3aed",
  },
  {
    id: 31,
    slug: "harkins-theatres",
    name: "Harkins Theatres",
    vertical: "Entertainment",
    location: "Scottsdale, AZ",
    description: "Regional movie theater chain loyalty and new release awareness",
    domain: "harkinstheatres.com",
    campaign: "Big Screen Summer 2026",
    budget: "$47,000",
    startDate: "May 8, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(23500),
    impressionsToDate: 2214800,
    reachToDate: 92400,
    completionRate: 81.4,
    primaryColor: "#b91c1c",
  },
  {
    id: 32,
    slug: "ra-sushi",
    name: "RA Sushi",
    vertical: "Casual Dining",
    location: "Scottsdale, AZ",
    description: "Japanese-fusion restaurant happy hour and event awareness",
    domain: "rasushi.com",
    campaign: "Happy Hour Elevated 2026",
    budget: "$39,000",
    startDate: "May 12, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(19500),
    impressionsToDate: 1887200,
    reachToDate: 78400,
    completionRate: 80.8,
    primaryColor: "#dc2626",
  },
  {
    id: 33,
    slug: "optimized-energy",
    name: "Optimized Energy",
    vertical: "Energy Solutions",
    location: "Scottsdale, AZ",
    description: "Commercial energy optimization and sustainability services",
    domain: "optimizedenergy.org",
    campaign: "Efficiency First 2026",
    budget: "$42,000",
    startDate: "May 12, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(21000),
    impressionsToDate: 1987200,
    reachToDate: 82400,
    completionRate: 81.9,
    primaryColor: "#16a34a",
  },
  {
    id: 34,
    slug: "paul-martinellis-investors-club",
    name: "Paul Martinelli's Investor's Club",
    vertical: "Investment & Finance",
    location: "Scottsdale, AZ",
    description: "Exclusive investment community membership acquisition campaign",
    domain: "paulmartielli.com",
    campaign: "Wealth Intelligence 2026",
    budget: "$54,000",
    startDate: "May 5, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(27000),
    impressionsToDate: 2587200,
    reachToDate: 108400,
    completionRate: 84.2,
    primaryColor: "#d97706",
  },
  {
    id: 35,
    slug: "lisa-chastain",
    name: "Lisa Chastain",
    vertical: "Business Coaching",
    location: "Phoenix, AZ",
    description: "Executive business coach brand awareness and program enrollment",
    domain: "lisachastain.com",
    campaign: "Lead with Purpose 2026",
    budget: "$28,000",
    startDate: "May 15, 2026",
    status: "active",
    hasDashboard: false,
    trend: risingTrend(14000),
    impressionsToDate: 1314800,
    reachToDate: 54400,
    completionRate: 78.1,
    primaryColor: "#ec4899",
  },
];
