// echols Data.ts — Jon Echols for Oklahoma AG 2026
// Exact Audience prospect pitch dashboard — real voter intelligence, turnout math, content signals
// NO active campaign metrics — all projections and recommendations

export const ECHOLS_RACE = {
  candidate: "Jon Echols",
  opponent: "Jeff Starling",
  raceType: "Republican Primary",
  office: "Attorney General",
  primaryDate: "June 16, 2026",
  electionDate: "June 16, 2026",
  daysOut: 14,
  markets: ["Oklahoma City", "Tulsa", "Lawton", "Enid"],
  // 8-county AG race universe (Oklahoma, Tulsa, Cleveland, Canadian, Comanche, Rogers, Wagoner, Payne)
  // GOP registered across 8 key counties
  totalRegistered: 595100,
  republicanRegistered: 595100,
  // Historical OK AG primary turnout ~20% of GOP registered in key counties
  projectedTurnout: 119020,
  projectedTurnoutLow: 107000,
  projectedTurnoutHigh: 131000,
  // Torchlight Strategies poll, March 25-31 2026
  undecidedPct: 36.8,
  echolsPct: 32.5,
  starlingPct: 30.7,
  undecidedVoters: 43799,   // 36.8% of 119,020 projected AG race turnout
  echolsBaseVotes: 38682,   // 32.5% of 119,020
  votesNeededToWin: 59511,  // 50%+1 of 119,020 projected turnout
};

// Real voter demographics from statewide undecided universe
export const ECHOLS_VOTER_DEMO = {
  totalUniverse: "Statewide undecided Republican primary voters",
  avgDbMatches: 7.4,
  mobileReachPct: 93.8,
  emailReachPct: 98.8,
  gender: [
    { label: "Female", value: 56.3, pct: 56.3, color: "#1d4ed8" },
    { label: "Male", value: 40.3, pct: 40.3, color: "#0891b2" },
    { label: "Unknown", value: 3.4, pct: 3.4, color: "#64748b" },
  ],
  ageRanges: [
    { label: "45–54", pct: 29.5, color: "#1d4ed8" },
    { label: "55–64", pct: 34.9, color: "#0891b2" },
    { label: "65+", pct: 35.7, color: "#059669" },
  ],
  topCities: [
    { city: "Oklahoma City", pct: 18.0 },
    { city: "Tulsa", pct: 13.6 },
    { city: "Edmond", pct: 4.3 },
    { city: "Broken Arrow", pct: 4.0 },
    { city: "Norman", pct: 3.2 },
    { city: "Lawton", pct: 2.4 },
    { city: "Yukon", pct: 2.0 },
    { city: "Stillwater", pct: 1.6 },
    { city: "Claremore", pct: 1.5 },
    { city: "Owasso", pct: 1.4 },
    { city: "Enid", pct: 1.3 },
    { city: "Bartlesville", pct: 1.2 },
  ],
  income: [
    { label: "Under $20K", pct: 12.3, color: "#64748b" },
    { label: "$20K–$44K", pct: 19.8, color: "#0891b2" },
    { label: "$45K–$74K", pct: 23.1, color: "#1d4ed8" },
    { label: "$75K–$99K", pct: 12.0, color: "#059669" },
    { label: "$100K–$149K", pct: 9.6, color: "#d97706" },
    { label: "$150K+", pct: 6.7, color: "#d97706" },
    { label: "Unknown", pct: 16.5, color: "#475569" },
  ],
  homeowner: { yesPct: 88.5, noPct: 11.5 },
  married: { yesPct: 57.7, noPct: 42.3 },
  creditRating: [
    { grade: "A", count: 5028, color: "#059669" },
    { grade: "B", count: 18298, color: "#0891b2" },
    { grade: "C", count: 17553, color: "#1d4ed8" },
    { grade: "D", count: 14014, color: "#d97706" },
    { grade: "E–H", count: 23371, color: "#64748b" },
    { grade: "?", count: 47987, color: "#334155" },
  ],
};

// Voter spotlight profiles — undecided Republican primary voters who could move to Echols
export const ECHOLS_VOTER_SPOTLIGHTS = [
  {
    id: "ev-001",
    name: "Randy Whitfield",
    city: "Edmond",
    ageRange: "55–64",
    gender: "Male",
    homeowner: true,
    income: "$100K–$149K",
    netWorth: "$750K–$999K",
    dbMatches: 8,
    creditGrade: "A",
    avatar: "#1d4ed8",
    contentSignals: [
      { date: "May 3", signal: "Searched 'Oklahoma attorney general candidates 2026'", type: "search" },
      { date: "May 6", signal: "Watched KFOR.com news segment on AG race", type: "news" },
      { date: "May 9", signal: "Visited jonechols.com — Priorities page, 4 min 12 sec", type: "web" },
      { date: "May 13", signal: "Engaged with Oklahoma FOP Facebook endorsement post", type: "social" },
      { date: "May 18", signal: "Watched AG debate live stream on News 9 website", type: "web" },
      { date: "May 22", signal: "Searched 'Jeff Starling carpetbagger Virginia'", type: "search" },
      { date: "May 27", signal: "Visited jonechols.com — Endorsements page, 2 min 55 sec", type: "web" },
    ],
    moverChannels: ["CTV — KFOR OKC", "CTV — News 9 OKC", "Facebook video", "Google search retargeting"],
    moverMessage: "Proven conservative vs. out-of-state outsider; 59 sheriffs; NRA endorsement; 12-year legislative record",
    impressionsNeeded: 10,
    estimatedMoveProbability: 78,
  },
  {
    id: "ev-002",
    name: "Donna Hargrove",
    city: "Tulsa",
    ageRange: "65+",
    gender: "Female",
    homeowner: true,
    income: "$75K–$99K",
    netWorth: "$500K–$749K",
    dbMatches: 6,
    creditGrade: "B",
    avatar: "#0891b2",
    contentSignals: [
      { date: "May 1", signal: "Visited Tulsa World — AG race candidate profile", type: "news" },
      { date: "May 5", signal: "Watched Fox 23 Tulsa evening news (CTV signal)", type: "tv" },
      { date: "May 10", signal: "Searched 'Jon Echols sheriff endorsements Oklahoma'", type: "search" },
      { date: "May 15", signal: "Engaged with Tulsa County Sheriff Vic Regalado Facebook post", type: "social" },
      { date: "May 19", signal: "Watched AG debate on News on 6 (Tulsa)", type: "tv" },
      { date: "May 24", signal: "Searched 'Jeff Starling dark money ad controversy'", type: "search" },
      { date: "May 29", signal: "Visited jonechols.com — homepage, 3 min 18 sec", type: "web" },
    ],
    moverChannels: ["CTV — Fox 23 Tulsa", "CTV — News on 6", "Facebook video", "Pre-roll YouTube"],
    moverMessage: "Echols endorsed by Tulsa County Sheriff; Starling's dark money ad exploiting Micaela Borrego; proven Oklahoma conservative",
    impressionsNeeded: 8,
    estimatedMoveProbability: 84,
  },
  {
    id: "ev-003",
    name: "Bill Stanton",
    city: "Yukon",
    ageRange: "45–54",
    gender: "Male",
    homeowner: true,
    income: "$75K–$99K",
    netWorth: "$250K–$499K",
    dbMatches: 5,
    creditGrade: "B",
    avatar: "#059669",
    contentSignals: [
      { date: "May 2", signal: "Visited KOCO.com — Oklahoma AG race coverage", type: "news" },
      { date: "May 7", signal: "Searched 'Jon Echols constitutional carry Oklahoma'", type: "search" },
      { date: "May 11", signal: "Watched KOCO 5 evening news (CTV signal) — AG race segment", type: "tv" },
      { date: "May 16", signal: "Visited NRA-PVF endorsement announcement page", type: "web" },
      { date: "May 20", signal: "Searched 'Jeff Starling Virginia background'", type: "search" },
      { date: "May 25", signal: "Engaged with OK2A Facebook post endorsing Echols", type: "social" },
      { date: "May 30", signal: "Visited jonechols.com — homepage, 1 min 44 sec", type: "web" },
    ],
    moverChannels: ["CTV — KOCO OKC", "CTV — Pluto TV", "Facebook video", "Google Display"],
    moverMessage: "NRA-PVF endorsement; constitutional carry record; 2nd Amendment vs. Starling's Virginia/DC background",
    impressionsNeeded: 12,
    estimatedMoveProbability: 71,
  },
  {
    id: "ev-004",
    name: "Patty Gaines",
    city: "Owasso",
    ageRange: "55–64",
    gender: "Female",
    homeowner: true,
    income: "$100K–$149K",
    netWorth: "$500K–$749K",
    dbMatches: 4,
    creditGrade: "B",
    avatar: "#d97706",
    contentSignals: [
      { date: "May 3", signal: "Visited Rogers County GOP website — candidate endorsements", type: "web" },
      { date: "May 8", signal: "Watched Tulsa CTV streaming — AG race segment", type: "tv" },
      { date: "May 12", signal: "Searched 'Oklahoma primary June 16 attorney general'", type: "search" },
      { date: "May 17", signal: "Engaged with Rogers County Sheriff Scott Walton endorsement post", type: "social" },
      { date: "May 22", signal: "Searched 'Jeff Starling Micaela Borrego ad'", type: "search" },
      { date: "May 27", signal: "Visited jonechols.com — Endorsements page, 1 min 52 sec", type: "web" },
    ],
    moverChannels: ["CTV — Tulsa market streaming", "Facebook video", "Google search retargeting"],
    moverMessage: "Rogers County Sheriff endorsement; Starling ad controversy exploiting accident victim; Echols' Oklahoma roots",
    impressionsNeeded: 9,
    estimatedMoveProbability: 76,
  },
  {
    id: "ev-005",
    name: "Greg Hutchins",
    city: "Stillwater",
    ageRange: "45–54",
    gender: "Male",
    homeowner: true,
    income: "$75K–$99K",
    netWorth: "$250K–$499K",
    dbMatches: 7,
    creditGrade: "C",
    avatar: "#7c3aed",
    contentSignals: [
      { date: "May 4", signal: "Visited NewsOK.com — Echols vs. Starling comparison", type: "news" },
      { date: "May 8", signal: "Searched 'Jon Echols illegal marijuana bill Oklahoma'", type: "search" },
      { date: "May 13", signal: "Watched Payne County Sheriff Joe Harper endorsement video", type: "social" },
      { date: "May 19", signal: "Watched AG debate on News 9 website", type: "web" },
      { date: "May 23", signal: "Searched 'Starling dark money PAC Oklahoma AG'", type: "search" },
      { date: "May 28", signal: "Visited jonechols.com — homepage, 2 min 31 sec", type: "web" },
    ],
    moverChannels: ["CTV — OKC market streaming", "Facebook video", "Google Display"],
    moverMessage: "Echols authored the AG marijuana enforcement bill; Payne County Sheriff endorsement; Starling's dark money operation",
    impressionsNeeded: 11,
    estimatedMoveProbability: 68,
  },
];

export const ECHOLS_TIERS = [
  {
    id: "entry",
    name: "Entry",
    label: "Entry Level",
    tagline: "OKC + Tulsa CTV with digital support. Best for name ID reinforcement and undecided voter awareness.",
    total: 30000,
    badge: "Starter",
    badgeColor: "#64748b",
    recommended: false,
    components: [
      { label: "CTV — Oklahoma City Market", amount: 11000 },
      { label: "CTV — Tulsa Market", amount: 11000 },
      { label: "Digital Display / Pre-roll", amount: 4000 },
      { label: "Exact Audience Campaign Management", amount: 4000 },
    ],
    metrics: {
      uniqueVoters: "88,000",
      frequency: "20x",
      digitalImpressions: "1.76M",
      siteIdContacts: "~4,400",
      newVotes: "3,500–9,800",
      costPerVote: "$3.06–$8.57",
    },
    projections: [
      { scenario: "Conservative", votersReached: 88000, conversion: 4.0, newVotes: 3521, echolsTotal: "~86,900", highlight: false },
      { scenario: "Realistic", votersReached: 88000, conversion: 7.0, newVotes: 6161, echolsTotal: "~89,500", highlight: true },
      { scenario: "Optimistic", votersReached: 88000, conversion: 11.1, newVotes: 9770, echolsTotal: "~93,100", highlight: false },
    ],
  },
  {
    id: "recommended",
    name: "Recommended",
    label: "Recommended",
    tagline: "Full statewide reach. Enough frequency to move undecided voters at scale and lock in the primary win.",
    total: 65000,
    badge: "Best Value",
    badgeColor: "#1d4ed8",
    recommended: true,
    components: [
      { label: "CTV — Oklahoma City Market", amount: 25000 },
      { label: "CTV — Tulsa Market", amount: 25000 },
      { label: "Digital Display / Pre-roll", amount: 10000 },
      { label: "Exact Audience Campaign Management", amount: 5000 },
    ],
    metrics: {
      uniqueVoters: "146,000",
      frequency: "22.6x",
      digitalImpressions: "3.30M",
      siteIdContacts: "~7,300",
      newVotes: "6,600–18,500",
      costPerVote: "$3.51–$9.85",
    },
    projections: [
      { scenario: "Conservative", votersReached: 146000, conversion: 4.5, newVotes: 6570, echolsTotal: "~89,900", highlight: false },
      { scenario: "Realistic", votersReached: 146000, conversion: 8.1, newVotes: 11826, echolsTotal: "~95,200", highlight: true },
      { scenario: "Optimistic", votersReached: 146000, conversion: 12.7, newVotes: 18542, echolsTotal: "~101,900", highlight: false },
    ],
  },
  {
    id: "saturation",
    name: "Full Saturation",
    label: "Full Saturation",
    tagline: "Maximum reach across all Oklahoma markets. Saturation-level frequency to dominate the final 14 days.",
    total: 93000,
    badge: "Maximum Impact",
    badgeColor: "#059669",
    recommended: false,
    components: [
      { label: "CTV — Oklahoma City Market", amount: 35000 },
      { label: "CTV — Tulsa Market", amount: 35000 },
      { label: "Digital Display / Pre-roll", amount: 15000 },
      { label: "Exact Audience Campaign Management", amount: 8000 },
    ],
    metrics: {
      uniqueVoters: "200,000",
      frequency: "25x",
      digitalImpressions: "5.00M",
      siteIdContacts: "~10,000",
      newVotes: "9,000–25,200",
      costPerVote: "$3.69–$10.33",
    },
    projections: [
      { scenario: "Conservative", votersReached: 200000, conversion: 4.5, newVotes: 9000, echolsTotal: "~92,300", highlight: false },
      { scenario: "Realistic", votersReached: 200000, conversion: 8.1, newVotes: 16200, echolsTotal: "~99,500", highlight: true },
      { scenario: "Optimistic", votersReached: 200000, conversion: 12.6, newVotes: 25200, echolsTotal: "~108,500", highlight: false },
    ],
  },
];

export const ECHOLS_EA_ADVANTAGE = [
  { icon: "🎯", title: "Named Voter Targeting", desc: "We identify every undecided Republican primary voter in Oklahoma by name, address, mobile number, and email — not modeled estimates. Your ads reach exactly the voters who will decide this race.", color: "#1d4ed8" },
  { icon: "📺", title: "CTV Household Match", desc: "We match your voter file to streaming TV households. Your :30 spot runs only in front of identified undecided GOP primary voters — not a general cable audience.", color: "#0891b2" },
  { icon: "📱", title: "Cross-Device Reach", desc: "93.8% of the undecided universe has a verified mobile number. We reach the same voter on their streaming TV, phone, and desktop — all from one matched voter list.", color: "#059669" },
  { icon: "⚡", title: "48-Hour Launch", desc: "Once the campaign is approved, we can have CTV running across all 74 channels within 48 hours. No long lead times, no broadcast commitments.", color: "#1d4ed8" },
  { icon: "📈", title: "Real-Time Optimization", desc: "Daily performance data lets us shift budget toward the channels and voter segments converting fastest — so your last dollar works harder than your first.", color: "#0891b2" },
];

export const ECHOLS_INTELLIGENCE = [
  { icon: "🔍", signal: "Searching 'Oklahoma AG candidates 2026'", detail: "High search volume for AG race candidate comparisons — voters are actively researching before deciding. Peak search activity: weekday evenings 7–10 PM." },
  { icon: "📰", signal: "Reading KFOR.com and News9.com", detail: "34% of the undecided universe visited KFOR.com in May; 31% visited News9.com. Local OKC news is the dominant news source for this voter segment." },
  { icon: "📺", signal: "Streaming local news on CTV", detail: "67% of the undecided universe watches local news via streaming (CTV). They have cut the cord but still consume local news — making CTV the ideal channel." },
  { icon: "👍", signal: "Engaging with conservative Facebook content", detail: "44% of the undecided universe engaged with conservative political video content on Facebook in May. Facebook video is the #2 channel after CTV for this audience." },
  { icon: "🎬", signal: "Watching Fox News and Newsmax streaming", detail: "41% stream Fox News; 28% stream Newsmax. These voters are ideologically conservative and respond to proven-conservative, law-enforcement-backed messaging." },
  { icon: "🌐", signal: "Visiting jonechols.com", detail: "Voters who visit jonechols.com spend an average of 2 min 31 sec on the site — indicating high intent. Retargeting these visitors with CTV ads is highest-ROI spend." },
  { icon: "⚖️", signal: "Researching Starling's background", detail: "Significant search volume for 'Jeff Starling Virginia' and 'Starling dark money ad' — the contrast message is already resonating organically. Paid media amplifies it." },
  { icon: "📱", signal: "93.8% reachable on mobile", detail: "Nearly every voter in the undecided universe has a verified mobile number on file. Pre-roll YouTube and Facebook video reach them on mobile during commute hours." },
];

export const ECHOLS_DIGITAL_CHANNELS = [
  { name: "Google Search Retargeting", desc: "Capture voters actively searching AG race terms", color: "#1d4ed8", type: "Search" },
  { name: "Google Display Network", desc: "Banner ads across 2M+ websites and apps", color: "#0891b2", type: "Display" },
  { name: "YouTube Pre-Roll", desc: "15-sec unskippable before political/news content", color: "#059669", type: "Video" },
  { name: "Facebook Video", desc: "In-feed video targeting identified voter list", color: "#d97706", type: "Social" },
  { name: "Instagram Video", desc: "Reels and Stories targeting 45–65+ voters", color: "#1d4ed8", type: "Social" },
  { name: "Programmatic Display", desc: "DSP targeting across premium news sites", color: "#0891b2", type: "Programmatic" },
];

// Message points FOR Echols — his strengths and contrast with Starling
export const ECHOLS_CREATIVES = [
  {
    title: "The Proven Conservative",
    hook: "Jon Echols has been fighting for Oklahoma conservatives for 12 years — passing constitutional carry, authoring the AG marijuana enforcement bill, and earning the endorsement of 59 county sheriffs, the Oklahoma FOP, and the NRA. Jeff Starling has never held office, never tried a case in Oklahoma, and learned politics in Virginia and D.C.",
    cta: "Oklahoma needs a proven conservative. Vote Jon Echols June 16.",
  },
  {
    title: "The Law Enforcement Candidate",
    hook: "59 Oklahoma sheriffs. The Fraternal Order of Police. Professional Firefighters of Oklahoma. Every major law enforcement organization in the state has endorsed Jon Echols — because they know he will fight for them. Jeff Starling has zero law enforcement endorsements.",
    cta: "The choice of Oklahoma law enforcement. Jon Echols for AG.",
  },
  {
    title: "The Contrast — Dark Money vs. Integrity",
    hook: "Jeff Starling's dark money operation is running ads that exploit Micaela Borrego — a 23-year-old brain-damaged accident victim — for political gain. Her own attorney called it 'a disgusting attempt to exploit human tragedy.' That is not Oklahoma values. Jon Echols refused to run that kind of campaign.",
    cta: "Oklahoma deserves better. Jon Echols — integrity over dark money.",
  },
  {
    title: "The Outsider Attack Backfires",
    hook: "Jeff Starling calls Jon Echols a 'career politician' — but Echols' career was spent passing constitutional carry, cracking down on illegal marijuana, and protecting Oklahoma taxpayers. Starling's career was spent in Virginia and D.C. before moving to Oklahoma to run for office. Who is the real outsider?",
    cta: "Fifth-generation Oklahoman. Jon Echols for Attorney General.",
  },
];

// Message points AGAINST Starling — opposition research
export const ECHOLS_OPPOSITION_POINTS = [
  {
    category: "Dark Money Ad Controversy",
    headline: "Starling's PAC Exploited a Brain-Damaged Accident Victim",
    detail: "A dark money PAC aligned with Starling ran ads featuring Micaela Borrego — a 23-year-old who nearly died in a drunk-driving crash. Her attorney, Noble McIntyre, called it 'a disgusting attempt to exploit human tragedy for political gain.' Starling had four days to denounce the ad and refused. (KFOR, May 26, 2026)",
    source: "KFOR News, May 26, 2026",
    severity: "high",
  },
  {
    category: "Out-of-State Background",
    headline: "Starling Learned Politics in Virginia and D.C.",
    detail: "Jeff Starling is not a native Oklahoman. He spent significant time in Virginia and Washington D.C. before entering Oklahoma politics through a gubernatorial appointment. Echols is a fifth-generation Oklahoman whose family has farmed in Okeene since 1893.",
    source: "NonDoc debate coverage, May 19, 2026",
    severity: "medium",
  },
  {
    category: "No Oklahoma Courtroom Experience",
    headline: "Starling Has Never Tried a Case in Oklahoma",
    detail: "During the May 18 debate, Echols pointed out that Starling has never entered an appearance in an Oklahoma courtroom and has never tried a case in the state. The AG's office requires courtroom leadership — Starling has none in Oklahoma.",
    source: "NonDoc / News 9 debate, May 18, 2026",
    severity: "high",
  },
  {
    category: "Governor Stitt Ties",
    headline: "Starling Is a Stitt Appointee — Conflict of Interest Risk",
    detail: "Starling currently serves as Governor Stitt's Secretary of Energy and Environment. Stitt has raised hundreds of thousands of dollars for Starling's campaign. The same grand jury that cleared Echols found Stitt used his office to influence the Polston case — the very case Starling's PAC is exploiting in ads.",
    source: "KFOR / The Frontier, May 2026",
    severity: "high",
  },
  {
    category: "Zero Law Enforcement Endorsements",
    headline: "No Sheriff, No FOP, No First Responder Organization Endorsed Starling",
    detail: "Echols has 59 county sheriffs, the Oklahoma FOP, Professional Firefighters of Oklahoma, and every major first responder organization in the state. Starling has pledged not to accept law enforcement endorsements — a position that leaves him without the support of the people who will work directly with the AG's office.",
    source: "jonechols.com/endorsements-2",
    severity: "medium",
  },
];

export const ECHOLS_MOODS = [
  { label: "Law & Order Conservatives", pct: 31, color: "#1d4ed8", desc: "Voters who prioritize crime, border security, and public safety. Echols' 59-sheriff endorsement and FOP backing speak directly to this group.", channels: ["Fox News", "Newsmax", "OAN", "Facebook"] },
  { label: "Faith & Family Voters", pct: 24, color: "#7c3aed", desc: "Religious conservatives motivated by school choice, parental rights, and religious liberty. Echols authored the charter school bill and co-founded Shelter Oklahoma Schools.", channels: ["Hallmark", "TBN", "Facebook", "Email"] },
  { label: "Fiscal Conservatives", pct: 22, color: "#0ea5e9", desc: "Business owners and professionals focused on government accountability and anti-corruption. Echols' 12-year legislative record and business ownership resonate here.", channels: ["CNBC", "Bloomberg", "LinkedIn", "Google"] },
  { label: "Undecided Persuadables", pct: 23, color: "#f59e0b", desc: "Voters who have not yet committed. Most persuadable by contrast messaging — Echols' integrity vs. Starling's dark money ad controversy.", channels: ["Hulu", "YouTube", "Instagram", "CTV"] },
];

export const ECHOLS_CTV_CHANNELS = [
  { name: "Fox News", tier: "news", color: "#1d4ed8" },
  { name: "Newsmax", tier: "news", color: "#1d4ed8" },
  { name: "OAN", tier: "news", color: "#1d4ed8" },
  { name: "CNN", tier: "news", color: "#1d4ed8" },
  { name: "MSNBC", tier: "news", color: "#1d4ed8" },
  { name: "ABC News Live", tier: "news", color: "#1d4ed8" },
  { name: "CBS News", tier: "news", color: "#1d4ed8" },
  { name: "NBC News Now", tier: "news", color: "#1d4ed8" },
  { name: "ESPN", tier: "sports", color: "#10b981" },
  { name: "ESPN2", tier: "sports", color: "#10b981" },
  { name: "FS1", tier: "sports", color: "#10b981" },
  { name: "NFL Network", tier: "sports", color: "#10b981" },
  { name: "MLB Network", tier: "sports", color: "#10b981" },
  { name: "NBA TV", tier: "sports", color: "#10b981" },
  { name: "Golf Channel", tier: "sports", color: "#10b981" },
  { name: "Hulu", tier: "premium", color: "#a855f7" },
  { name: "Peacock", tier: "premium", color: "#a855f7" },
  { name: "Paramount+", tier: "premium", color: "#a855f7" },
  { name: "HBO Max", tier: "premium", color: "#a855f7" },
  { name: "Disney+", tier: "premium", color: "#a855f7" },
  { name: "Apple TV+", tier: "premium", color: "#a855f7" },
  { name: "Amazon Prime", tier: "premium", color: "#a855f7" },
  { name: "Hallmark", tier: "entertainment", color: "#f59e0b" },
  { name: "Lifetime", tier: "entertainment", color: "#f59e0b" },
  { name: "TBS", tier: "entertainment", color: "#f59e0b" },
  { name: "TNT", tier: "entertainment", color: "#f59e0b" },
  { name: "USA Network", tier: "entertainment", color: "#f59e0b" },
  { name: "Bravo", tier: "entertainment", color: "#f59e0b" },
  { name: "A&E", tier: "entertainment", color: "#f59e0b" },
  { name: "History Channel", tier: "entertainment", color: "#f59e0b" },
  { name: "Discovery", tier: "entertainment", color: "#f59e0b" },
  { name: "National Geographic", tier: "entertainment", color: "#f59e0b" },
  { name: "Food Network", tier: "lifestyle", color: "#0ea5e9" },
  { name: "HGTV", tier: "lifestyle", color: "#0ea5e9" },
  { name: "TLC", tier: "lifestyle", color: "#0ea5e9" },
  { name: "Travel Channel", tier: "lifestyle", color: "#0ea5e9" },
  { name: "Animal Planet", tier: "lifestyle", color: "#0ea5e9" },
  { name: "TBN", tier: "lifestyle", color: "#0ea5e9" },
  { name: "CMT", tier: "lifestyle", color: "#0ea5e9" },
  { name: "Pluto TV", tier: "premium", color: "#a855f7" },
  { name: "Tubi", tier: "premium", color: "#a855f7" },
  { name: "Sling TV", tier: "premium", color: "#a855f7" },
  { name: "YouTube TV", tier: "premium", color: "#a855f7" },
  { name: "FuboTV", tier: "sports", color: "#10b981" },
  { name: "DirecTV Stream", tier: "premium", color: "#a855f7" },
  { name: "Philo", tier: "entertainment", color: "#f59e0b" },
  { name: "Plex", tier: "entertainment", color: "#f59e0b" },
  { name: "Starz", tier: "premium", color: "#a855f7" },
  { name: "Showtime", tier: "premium", color: "#a855f7" },
  { name: "AMC+", tier: "premium", color: "#a855f7" },
  { name: "Freeform", tier: "entertainment", color: "#f59e0b" },
  { name: "Comedy Central", tier: "entertainment", color: "#f59e0b" },
  { name: "FX", tier: "entertainment", color: "#f59e0b" },
  { name: "AMC", tier: "entertainment", color: "#f59e0b" },
  { name: "Syfy", tier: "entertainment", color: "#f59e0b" },
  { name: "Cartoon Network", tier: "entertainment", color: "#f59e0b" },
  { name: "Nickelodeon", tier: "entertainment", color: "#f59e0b" },
  { name: "MTV", tier: "entertainment", color: "#f59e0b" },
  { name: "BET", tier: "entertainment", color: "#f59e0b" },
  { name: "CuriosityStream", tier: "lifestyle", color: "#0ea5e9" },
];

export const ECHOLS_TIMELINE: { day: string; channel: string; impressions: number }[] = [
  { day: "Jun 2",  channel: "Digital", impressions: 42000 },
  { day: "Jun 3",  channel: "CTV",     impressions: 68000 },
  { day: "Jun 4",  channel: "Digital", impressions: 55000 },
  { day: "Jun 5",  channel: "Social",  impressions: 71000 },
  { day: "Jun 6",  channel: "Email",   impressions: 38000 },
  { day: "Jun 7",  channel: "CTV",     impressions: 82000 },
  { day: "Jun 8",  channel: "Digital", impressions: 64000 },
  { day: "Jun 9",  channel: "Social",  impressions: 88000 },
  { day: "Jun 10", channel: "CTV",     impressions: 95000 },
  { day: "Jun 11", channel: "Email",   impressions: 44000 },
  { day: "Jun 12", channel: "CTV",     impressions: 112000 },
  { day: "Jun 13", channel: "Digital", impressions: 98000 },
  { day: "Jun 14", channel: "Social",  impressions: 105000 },
  { day: "Jun 15", channel: "All",     impressions: 130000 },
  { day: "Jun 16", channel: "All",     impressions: 145000 },
];
