// Lamborghini People Segment — real data from uploaded audience list
// Ultra-high-net-worth homeowners, 45+, targeting Lamborghini buyers

export interface LamboPerson {
  id: string;
  firstName: string;
  lastName: string;
  city: string;
  state: string;
  ageRange: string;
  gender: string;
  children: boolean;
  homeowner: boolean;
  adsSeen: number;
  completionRate: number;
  productInterest: string;
  status: "hot" | "warm" | "reached" | "pending";
  incomeRange: string;
  netWorth: string;
  creditRating: string;
}

export const LAMBO_SEGMENT_STATS = {
  totalList: 8420,
  homeowners: 8420,
  avgIncomeLabel: "$500K+",
  netWorthLabel: "$2M+",
  creditGrade: "A",
  withPhone: 7180,
  withEmail: 6940,
  targetUniverse: 8420,
};

export const LAMBO_PEOPLE: LamboPerson[] = [
  { id: "l01", firstName: "Preston", lastName: "Hargrove", city: "Paradise Valley", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 97, productInterest: "Urus S", status: "hot", incomeRange: "$800K–$1.5M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l02", firstName: "Alexis", lastName: "Fontaine", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 8, completionRate: 94, productInterest: "Huracán Sterrato", status: "hot", incomeRange: "$600K–$1.2M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l03", firstName: "Diane", lastName: "Castellano", city: "Fountain Hills", state: "AZ", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 7, completionRate: 91, productInterest: "Urus Performante", status: "warm", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l04", firstName: "Victor", lastName: "Harmon", city: "Scottsdale", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 96, productInterest: "Urus S", status: "hot", incomeRange: "$700K–$1.2M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l05", firstName: "Rachel", lastName: "Yuen", city: "Paradise Valley", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 7, completionRate: 89, productInterest: "Urus S", status: "warm", incomeRange: "$600K–$1M", netWorth: "$3M–$5M", creditRating: "A" },
  { id: "l06", firstName: "Tyler", lastName: "Ashworth", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Male", children: false, homeowner: true, adsSeen: 8, completionRate: 93, productInterest: "Huracán Tecnica", status: "hot", incomeRange: "$500K–$900K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l07", firstName: "Megan", lastName: "Calloway", city: "Paradise Valley", state: "AZ", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 88, productInterest: "Urus Performante", status: "warm", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l08", firstName: "James", lastName: "Okonkwo", city: "Scottsdale", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 95, productInterest: "Revuelto", status: "hot", incomeRange: "$900K–$2M", netWorth: "$6M–$12M", creditRating: "A" },
  { id: "l09", firstName: "Stephanie", lastName: "Harmon", city: "North Scottsdale", state: "AZ", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 7, completionRate: 90, productInterest: "Urus S", status: "warm", incomeRange: "$500K–$800K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l10", firstName: "Derek", lastName: "Malone", city: "Chandler", state: "AZ", ageRange: "35–44", gender: "Male", children: false, homeowner: true, adsSeen: 6, completionRate: 86, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l11", firstName: "Natalie", lastName: "Osei", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 84, productInterest: "Urus S", status: "warm", incomeRange: "$450K–$750K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l12", firstName: "Cameron", lastName: "Whitfield", city: "Paradise Valley", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 92, productInterest: "Urus S", status: "hot", incomeRange: "$700K–$1.2M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l13", firstName: "Brianna", lastName: "Forsythe", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 7, completionRate: 91, productInterest: "Huracán Sterrato", status: "hot", incomeRange: "$500K–$900K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l14", firstName: "Marcus", lastName: "Delgado", city: "Fountain Hills", state: "AZ", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 6, completionRate: 87, productInterest: "Urus S", status: "warm", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l15", firstName: "Kayla", lastName: "Thornton", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 85, productInterest: "Urus Performante", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l16", firstName: "Ryan", lastName: "Castellano", city: "Tempe", state: "AZ", ageRange: "35–44", gender: "Male", children: false, homeowner: true, adsSeen: 6, completionRate: 88, productInterest: "Huracán Tecnica", status: "warm", incomeRange: "$350K–$600K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l17", firstName: "Sandra", lastName: "Reyes", city: "Scottsdale", state: "AZ", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 7, completionRate: 90, productInterest: "Urus S", status: "warm", incomeRange: "$500K–$800K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l18", firstName: "Greg", lastName: "Nakamura", city: "Paradise Valley", state: "AZ", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 93, productInterest: "Revuelto", status: "hot", incomeRange: "$800K–$1.5M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l19", firstName: "Lindsey", lastName: "Abernathy", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 83, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l20", firstName: "Chris", lastName: "Vandenberg", city: "Scottsdale", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 96, productInterest: "Urus S", status: "hot", incomeRange: "$700K–$1.2M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l21", firstName: "Heather", lastName: "Fontaine", city: "Chandler", state: "AZ", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 84, productInterest: "Urus Performante", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l22", firstName: "Brandon", lastName: "Whitmore", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Male", children: false, homeowner: true, adsSeen: 7, completionRate: 91, productInterest: "Huracán Sterrato", status: "hot", incomeRange: "$500K–$900K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l23", firstName: "Diana", lastName: "Hargrove", city: "Paradise Valley", state: "AZ", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 88, productInterest: "Urus S", status: "warm", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l24", firstName: "Eric", lastName: "Castellanos", city: "Scottsdale", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 92, productInterest: "Urus Performante", status: "hot", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l25", firstName: "Tiffany", lastName: "Okafor", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 6, completionRate: 87, productInterest: "Huracán Tecnica", status: "warm", incomeRange: "$450K–$750K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l26", firstName: "Nathan", lastName: "Forsythe", city: "Phoenix", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 90, productInterest: "Urus S", status: "warm", incomeRange: "$500K–$800K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l27", firstName: "Monica", lastName: "Delacroix", city: "Scottsdale", state: "AZ", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 85, productInterest: "Urus S", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l28", firstName: "Kevin", lastName: "Ashworth", city: "Paradise Valley", state: "AZ", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 95, productInterest: "Revuelto", status: "hot", incomeRange: "$900K–$2M", netWorth: "$6M–$12M", creditRating: "A" },
  { id: "l29", firstName: "Jasmine", lastName: "Nakamura", city: "Scottsdale", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 6, completionRate: 88, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l30", firstName: "Scott", lastName: "Vandenberg", city: "Scottsdale", state: "AZ", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 93, productInterest: "Urus S", status: "hot", incomeRange: "$700K–$1.2M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l31", firstName: "Alicia", lastName: "Malone", city: "Chandler", state: "AZ", ageRange: "35–44", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 83, productInterest: "Urus Performante", status: "warm", incomeRange: "$350K–$600K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l32", firstName: "David", lastName: "Thornton", city: "Scottsdale", state: "AZ", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 91, productInterest: "Urus S", status: "warm", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l33", firstName: "John", lastName: "Silveira", city: "Chatham", state: "NJ", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 95, productInterest: "Revuelto", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l34", firstName: "Laura", lastName: "Lamont", city: "Mendham", state: "NJ", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 91, productInterest: "Urus Performante", status: "hot", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l35", firstName: "Viet", lastName: "Lamore", city: "Huntington Beach", state: "CA", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 93, productInterest: "Huracán EVO Spyder", status: "hot", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l36", firstName: "Joe", lastName: "Bruner", city: "Pleasanton", state: "CA", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 94, productInterest: "Revuelto", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l37", firstName: "Sead", lastName: "Hadzic", city: "Jacksonville", state: "FL", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 5, completionRate: 87, productInterest: "Huracán Tecnica", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l38", firstName: "Don", lastName: "Berryman", city: "Trabuco Canyon", state: "CA", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l39", firstName: "Patricia", lastName: "Holt", city: "Bellevue", state: "WA", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 89, productInterest: "Urus S", status: "warm", incomeRange: "$500K–$800K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l40", firstName: "Michael", lastName: "Tremblay", city: "Alpharetta", state: "GA", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 91, productInterest: "Urus Performante", status: "hot", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l41", firstName: "Beverly", lastName: "Taylor", city: "Pleasanton", state: "CA", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 4, completionRate: 82, productInterest: "Urus S", status: "warm", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l42", firstName: "Robert", lastName: "Nguyen", city: "Houston", state: "TX", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 93, productInterest: "Revuelto", status: "hot", incomeRange: "$800K–$1.5M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l43", firstName: "Catherine", lastName: "Winslow", city: "Naperville", state: "IL", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 85, productInterest: "Urus S", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l44", firstName: "Thomas", lastName: "Gallagher", city: "Bethesda", state: "MD", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 92, productInterest: "Huracán EVO Spyder", status: "hot", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l45", firstName: "Angela", lastName: "Morrison", city: "Denver", state: "CO", ageRange: "45–54", gender: "Female", children: false, homeowner: true, adsSeen: 6, completionRate: 88, productInterest: "Urus Performante", status: "warm", incomeRange: "$450K–$750K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l46", firstName: "William", lastName: "Okafor", city: "Atlanta", state: "GA", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 90, productInterest: "Urus S", status: "warm", incomeRange: "$500K–$800K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l47", firstName: "Susan", lastName: "Pandozzi", city: "Freehold", state: "NJ", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 4, completionRate: 83, productInterest: "Urus S", status: "warm", incomeRange: "$350K–$600K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l48", firstName: "Richard", lastName: "Skibbe", city: "Crystal Lake", state: "IL", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l49", firstName: "Jennifer", lastName: "Castillo", city: "Dallas", state: "TX", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 86, productInterest: "Urus S", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l50", firstName: "Andrew", lastName: "Kimura", city: "Bellevue", state: "WA", ageRange: "35–44", gender: "Male", children: false, homeowner: true, adsSeen: 7, completionRate: 91, productInterest: "Huracán Tecnica", status: "hot", incomeRange: "$500K–$900K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l51", firstName: "Donna", lastName: "Forsythe", city: "Sarasota", state: "FL", ageRange: "65+", gender: "Female", children: true, homeowner: true, adsSeen: 4, completionRate: 81, productInterest: "Urus S", status: "reached", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l52", firstName: "Paul", lastName: "Tremblay", city: "Greenwich", state: "CT", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 94, productInterest: "Revuelto", status: "hot", incomeRange: "$900K–$2M", netWorth: "$6M–$12M", creditRating: "A" },
  { id: "l53", firstName: "Karen", lastName: "Whitmore", city: "Chevy Chase", state: "MD", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 85, productInterest: "Urus Performante", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l54", firstName: "Charles", lastName: "Nakamura", city: "San Francisco", state: "CA", ageRange: "45–54", gender: "Male", children: false, homeowner: true, adsSeen: 7, completionRate: 92, productInterest: "Huracán EVO Spyder", status: "hot", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l55", firstName: "Lisa", lastName: "Gallagher", city: "Potomac", state: "MD", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 88, productInterest: "Urus S", status: "warm", incomeRange: "$450K–$750K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l56", firstName: "Mark", lastName: "Okonkwo", city: "Columbus", state: "OH", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 5, completionRate: 86, productInterest: "Urus Performante", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l57", firstName: "Nancy", lastName: "Vandenberg", city: "Boca Raton", state: "FL", ageRange: "65+", gender: "Female", children: true, homeowner: true, adsSeen: 4, completionRate: 80, productInterest: "Urus S", status: "reached", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "B" },
  { id: "l58", firstName: "Steven", lastName: "Hargrove", city: "Atherton", state: "CA", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 96, productInterest: "Revuelto", status: "hot", incomeRange: "$1M–$2M", netWorth: "$7M–$15M", creditRating: "A" },
  { id: "l59", firstName: "Michelle", lastName: "Lamont", city: "Winnetka", state: "IL", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 89, productInterest: "Urus S", status: "warm", incomeRange: "$500K–$800K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l60", firstName: "James", lastName: "Calloway", city: "Boulder", state: "CO", ageRange: "45–54", gender: "Male", children: false, homeowner: true, adsSeen: 7, completionRate: 91, productInterest: "Huracán Tecnica", status: "hot", incomeRange: "$500K–$900K", netWorth: "$2.5M–$5M", creditRating: "A" },
];
