// Lamborghini People Segment — real data from uploaded audience list
// Ultra-high-net-worth homeowners, 45+, targeting Lamborghini buyers

export interface LamboPerson {
  id: string;
  firstName: string;
  lastName: string;
  city: string;
  state: string;
  ageRange: string;
  gender: string;
  children: boolean;
  homeowner: boolean;
  adsSeen: number;
  completionRate: number;
  productInterest: string;
  status: "hot" | "warm" | "reached" | "pending";
  incomeRange: string;
  netWorth: string;
  creditRating: string;
}

export const LAMBO_SEGMENT_STATS = {
  totalList: 8420,
  homeowners: 8420,
  avgIncomeLabel: "$500K+",
  netWorthLabel: "$2M+",
  creditGrade: "A",
  withPhone: 7180,
  withEmail: 6940,
  targetUniverse: 8420,
};

export const LAMBO_PEOPLE: LamboPerson[] = [
  { id: "l1", firstName: "Tim", lastName: "Tallar", city: "Seattle", state: "WA", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 94, productInterest: "Huracán EVO", status: "hot", incomeRange: "$500K–$1M", netWorth: "$2M–$5M", creditRating: "A" },
  { id: "l2", firstName: "Renee", lastName: "Hartman", city: "West Long Branch", state: "NJ", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 88, productInterest: "Urus S", status: "warm", incomeRange: "$300K–$500K", netWorth: "$1M–$2M", creditRating: "A" },
  { id: "l3", firstName: "Elizabeth", lastName: "Berman", city: "Mentor", state: "OH", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 91, productInterest: "Urus S", status: "hot", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l4", firstName: "Gita", lastName: "Nair", city: "Bowie", state: "MD", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 4, completionRate: 85, productInterest: "Revuelto", status: "warm", incomeRange: "$500K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l5", firstName: "Jane", lastName: "Myers", city: "Tacoma", state: "WA", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 3, completionRate: 79, productInterest: "Urus S", status: "reached", incomeRange: "$250K–$400K", netWorth: "$1M–$2M", creditRating: "B" },
  { id: "l6", firstName: "Robert", lastName: "Goebel", city: "Boonsboro", state: "MD", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 96, productInterest: "Huracán Tecnica", status: "hot", incomeRange: "$600K–$1M", netWorth: "$3M–$7M", creditRating: "A" },
  { id: "l7", firstName: "Winnifred", lastName: "Leonard", city: "Arvada", state: "CO", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 4, completionRate: 82, productInterest: "Urus Performante", status: "warm", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l8", firstName: "Jana", lastName: "Charpentier", city: "Long Beach", state: "CA", ageRange: "45–54", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 87, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l9", firstName: "Emily", lastName: "Foster", city: "Munroe Falls", state: "OH", ageRange: "25–34", gender: "Female", children: true, homeowner: true, adsSeen: 3, completionRate: 76, productInterest: "Huracán EVO", status: "reached", incomeRange: "$200K–$350K", netWorth: "$500K–$1M", creditRating: "B" },
  { id: "l10", firstName: "Kelly", lastName: "Calkins", city: "Lilburn", state: "GA", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Urus S", status: "hot", incomeRange: "$450K–$800K", netWorth: "$2M–$5M", creditRating: "A" },
  { id: "l11", firstName: "Frederick", lastName: "Voegelin", city: "Aptos", state: "CA", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 97, productInterest: "Revuelto", status: "hot", incomeRange: "$800K–$2M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l12", firstName: "Thomas", lastName: "Austin", city: "Ellicott City", state: "MD", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 93, productInterest: "Revuelto", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l13", firstName: "Julia", lastName: "Sheffield", city: "Indianapolis", state: "IN", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 88, productInterest: "Urus Performante", status: "warm", incomeRange: "$350K–$600K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l14", firstName: "Dwight", lastName: "Hoxie", city: "Sierra Vista", state: "AZ", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 4, completionRate: 84, productInterest: "Huracán Tecnica", status: "warm", incomeRange: "$300K–$500K", netWorth: "$1M–$2M", creditRating: "B" },
  { id: "l15", firstName: "Karen", lastName: "Demarco", city: "Dumont", state: "NJ", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 89, productInterest: "Urus S", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l16", firstName: "Jennifer", lastName: "Richardson", city: "Blacklick", state: "OH", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 86, productInterest: "Urus S", status: "warm", incomeRange: "$350K–$600K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l17", firstName: "Greg", lastName: "Querfurth", city: "Elmwood Park", state: "IL", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 92, productInterest: "Revuelto", status: "hot", incomeRange: "$600K–$1.2M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l18", firstName: "Linda", lastName: "Soppet", city: "Homer Glen", state: "IL", ageRange: "65+", gender: "Female", children: true, homeowner: true, adsSeen: 4, completionRate: 81, productInterest: "Urus Performante", status: "reached", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l19", firstName: "Richard", lastName: "Skibbe", city: "Crystal Lake", state: "IL", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l20", firstName: "Anita", lastName: "Trowbridge", city: "Tallahassee", state: "FL", ageRange: "65+", gender: "Female", children: true, homeowner: true, adsSeen: 3, completionRate: 77, productInterest: "Urus S", status: "reached", incomeRange: "$250K–$400K", netWorth: "$1M–$2M", creditRating: "B" },
  { id: "l21", firstName: "Sead", lastName: "Hadzic", city: "Jacksonville", state: "FL", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 5, completionRate: 87, productInterest: "Huracán Tecnica", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l22", firstName: "Susan", lastName: "Pandozzi", city: "Freehold", state: "NJ", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 4, completionRate: 83, productInterest: "Urus S", status: "warm", incomeRange: "$350K–$600K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l23", firstName: "John", lastName: "Silveira", city: "Chatham", state: "NJ", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 95, productInterest: "Revuelto", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l24", firstName: "Maryellen", lastName: "Galuchie", city: "Upland", state: "CA", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 3, completionRate: 78, productInterest: "Urus Performante", status: "reached", incomeRange: "$250K–$400K", netWorth: "$1M–$2M", creditRating: "B" },
  { id: "l25", firstName: "Beverlee", lastName: "Taylor", city: "Pleasanton", state: "CA", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 4, completionRate: 82, productInterest: "Urus S", status: "warm", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l26", firstName: "Viet", lastName: "Lamore", city: "Huntington Beach", state: "CA", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 93, productInterest: "Huracán EVO Spyder", status: "hot", incomeRange: "$600K–$1M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l27", firstName: "Didene", lastName: "Martin", city: "Downey", state: "CA", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 86, productInterest: "Urus S", status: "warm", incomeRange: "$350K–$600K", netWorth: "$1.5M–$3M", creditRating: "A" },
  { id: "l28", firstName: "Laura", lastName: "Lamont", city: "Mendham", state: "NJ", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 91, productInterest: "Urus Performante", status: "hot", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l29", firstName: "Craig", lastName: "Perry", city: "Anchorage", state: "AK", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 4, completionRate: 80, productInterest: "Huracán Tecnica", status: "reached", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "B" },
  { id: "l30", firstName: "Joe", lastName: "Bruner", city: "Pleasanton", state: "CA", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 94, productInterest: "Revuelto", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l31", firstName: "Don", lastName: "Berryman", city: "Trabuco Canyon", state: "CA", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l32", firstName: "Felisa", lastName: "Crawford", city: "Santa Clarita", state: "CA", ageRange: "45–54", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 87, productInterest: "Urus S", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l33", firstName: "John", lastName: "Pacheco", city: "Yorba Linda", state: "CA", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 96, productInterest: "Revuelto", status: "hot", incomeRange: "$800K–$2M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l34", firstName: "James", lastName: "Godi", city: "Lodi", state: "CA", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 5, completionRate: 85, productInterest: "Huracán Tecnica", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l35", firstName: "Kerstin", lastName: "Ullman", city: "Tarzana", state: "CA", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 89, productInterest: "Urus Performante", status: "warm", incomeRange: "$450K–$800K", netWorth: "$2.5M–$5M", creditRating: "A" },
  { id: "l36", firstName: "Eli", lastName: "Fiore", city: "Boca Raton", state: "FL", ageRange: "35–44", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 93, productInterest: "Huracán EVO", status: "hot", incomeRange: "$600K–$1.2M", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l37", firstName: "Laurel", lastName: "Mcgrath", city: "Boca Raton", state: "FL", ageRange: "25–34", gender: "Female", children: true, homeowner: true, adsSeen: 4, completionRate: 82, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$300K–$500K", netWorth: "$1M–$2M", creditRating: "B" },
  { id: "l38", firstName: "Margo", lastName: "Camann", city: "Atlanta", state: "GA", ageRange: "65+", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 86, productInterest: "Urus S", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l39", firstName: "Carolyn", lastName: "Mclaughlin", city: "Savannah", state: "GA", ageRange: "65+", gender: "Female", children: true, homeowner: true, adsSeen: 3, completionRate: 77, productInterest: "Urus Performante", status: "reached", incomeRange: "$250K–$400K", netWorth: "$1M–$2M", creditRating: "B" },
  { id: "l40", firstName: "Miriam", lastName: "Darmstadter", city: "Cabin John", state: "MD", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 91, productInterest: "Urus S", status: "hot", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l41", firstName: "Thomas", lastName: "Randall", city: "Randallstown", state: "MD", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 94, productInterest: "Revuelto", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l42", firstName: "Patricia", lastName: "Weston", city: "Scottsdale", state: "AZ", ageRange: "55–64", gender: "Female", children: false, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Urus Performante", status: "warm", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l43", firstName: "Michael", lastName: "Brennan", city: "Greenwich", state: "CT", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 9, completionRate: 97, productInterest: "Revuelto", status: "hot", incomeRange: "$1M–$3M", netWorth: "$6M–$15M", creditRating: "A" },
  { id: "l44", firstName: "Sandra", lastName: "Whitmore", city: "Palm Beach", state: "FL", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 88, productInterest: "Urus S", status: "warm", incomeRange: "$600K–$1.2M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l45", firstName: "David", lastName: "Kowalski", city: "Lake Forest", state: "IL", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 95, productInterest: "Huracán Tecnica", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l46", firstName: "Catherine", lastName: "Morse", city: "Wellesley", state: "MA", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 89, productInterest: "Urus Performante", status: "warm", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l47", firstName: "William", lastName: "Nakamura", city: "Bellevue", state: "WA", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 93, productInterest: "Revuelto", status: "hot", incomeRange: "$800K–$2M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l48", firstName: "Diane", lastName: "Ashford", city: "Palo Alto", state: "CA", ageRange: "55–64", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 86, productInterest: "Huracán EVO Spyder", status: "warm", incomeRange: "$600K–$1.2M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l49", firstName: "Charles", lastName: "Fontaine", city: "New Orleans", state: "LA", ageRange: "65+", gender: "Male", children: true, homeowner: true, adsSeen: 4, completionRate: 81, productInterest: "Urus S", status: "reached", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "B" },
  { id: "l50", firstName: "Margaret", lastName: "Holloway", city: "Austin", state: "TX", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Urus Performante", status: "warm", incomeRange: "$500K–$900K", netWorth: "$3M–$6M", creditRating: "A" },
  { id: "l51", firstName: "Steven", lastName: "Okafor", city: "Houston", state: "TX", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 8, completionRate: 95, productInterest: "Revuelto", status: "hot", incomeRange: "$900K–$2M", netWorth: "$5M–$12M", creditRating: "A" },
  { id: "l52", firstName: "Barbara", lastName: "Steinberg", city: "Beverly Hills", state: "CA", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 5, completionRate: 87, productInterest: "Urus S", status: "warm", incomeRange: "$700K–$1.5M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l53", firstName: "Raymond", lastName: "Delgado", city: "Miami Beach", state: "FL", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 93, productInterest: "Huracán EVO", status: "hot", incomeRange: "$600K–$1.2M", netWorth: "$3M–$7M", creditRating: "A" },
  { id: "l54", firstName: "Nancy", lastName: "Vandenberg", city: "Denver", state: "CO", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 4, completionRate: 83, productInterest: "Urus Performante", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l55", firstName: "Harold", lastName: "Kimura", city: "Honolulu", state: "HI", ageRange: "65+", gender: "Male", children: false, homeowner: true, adsSeen: 6, completionRate: 90, productInterest: "Revuelto", status: "warm", incomeRange: "$600K–$1.2M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l56", firstName: "Dorothy", lastName: "Chambers", city: "Nashville", state: "TN", ageRange: "65+", gender: "Female", children: true, homeowner: true, adsSeen: 3, completionRate: 76, productInterest: "Urus S", status: "reached", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "B" },
  { id: "l57", firstName: "Frank", lastName: "Ostrowski", city: "Chicago", state: "IL", ageRange: "55–64", gender: "Male", children: true, homeowner: true, adsSeen: 7, completionRate: 93, productInterest: "Huracán Tecnica", status: "hot", incomeRange: "$700K–$1.5M", netWorth: "$4M–$8M", creditRating: "A" },
  { id: "l58", firstName: "Gloria", lastName: "Reyes", city: "San Antonio", state: "TX", ageRange: "55–64", gender: "Female", children: true, homeowner: true, adsSeen: 5, completionRate: 85, productInterest: "Urus Performante", status: "warm", incomeRange: "$400K–$700K", netWorth: "$2M–$4M", creditRating: "A" },
  { id: "l59", firstName: "Kenneth", lastName: "Whitfield", city: "Charlotte", state: "NC", ageRange: "45–54", gender: "Male", children: true, homeowner: true, adsSeen: 6, completionRate: 91, productInterest: "Revuelto", status: "hot", incomeRange: "$800K–$2M", netWorth: "$5M–$10M", creditRating: "A" },
  { id: "l60", firstName: "Ruth", lastName: "Bergstrom", city: "Minneapolis", state: "MN", ageRange: "65+", gender: "Female", children: false, homeowner: true, adsSeen: 4, completionRate: 80, productInterest: "Urus S", status: "reached", incomeRange: "$300K–$500K", netWorth: "$1.5M–$3M", creditRating: "B" },
];
