// Exact Audience — TV Network & Streamer Logo Map
// Uses Google's favicon service (sz=128) for reliable logo retrieval.
// Niche/obscure networks without a strong favicon get styled initials badges instead.

const G = (domain: string) =>
  `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

// Networks that don't have a useful favicon — use initials badge in UI
export const INITIALS_ONLY = new Set([
  "Stirr", "NewsON", "Kanopy", "Epoch TV", "America's Voice",
  "GSN", "Game Show Network", "Ovation", "Sundance TV", "IFC",
  "WE tv", "Logo TV", "Pop TV", "Reelz", "Fuse", "Viceland",
  "Cheddar", "Newsy", "i24 News", "CuriosityStream", "Acorn TV",
  "BritBox", "Shudder", "Sundance Now", "Topic", "Mubi",
  "MotorTrend", "Outside TV", "Outdoor Channel", "Sportsman Channel",
  "World Fishing Network", "Pursuit Channel", "Carbon TV",
  "FYI", "LMN", "Viceland", "Aspire", "INSP", "Hallmark Movies",
  "UPtv", "Dove Channel", "Pure Flix", "Great American Family",
  "Charge!", "Comet", "Grit TV", "Heroes & Icons", "MeTV",
  "Antenna TV", "Decades", "Start TV", "Laff", "Court TV Mystery",
  "True Crime Network", "Justice Network", "Crime + Investigation",
  "Magnolia Network", "Chip and Joanna", "Tastemade",
  "Vix+", "ViX", "Univision", "Telemundo", "Estrella TV",
  "Performance Network", "DSP Display",
]);

export const NETWORK_LOGOS: Record<string, string> = {
  // ── Major Streaming Platforms ────────────────────────────────────────────
  "Samsung TV Plus":        G("samsungtvplus.com"),
  "Roku Channel":           G("roku.com"),
  "Tubi":                   G("tubi.tv"),
  "Pluto TV":               G("pluto.tv"),
  "Sling TV":               G("sling.com"),
  "DIRECTV":                G("directv.com"),
  "DIRECTV STREAM":         G("directv.com"),
  "Peacock":                G("peacocktv.com"),
  "Hulu":                   G("hulu.com"),
  "Amazon Freevee":         G("amazon.com"),
  "Amazon Prime Video":     G("primevideo.com"),
  "Paramount+":             G("paramountplus.com"),
  "Discovery+":             G("discoveryplus.com"),
  "Max":                    G("max.com"),
  "HBO Max":                G("max.com"),
  "Apple TV+":              G("tv.apple.com"),
  "Disney+":                G("disneyplus.com"),
  "Netflix":                G("netflix.com"),
  "fuboTV":                 G("fubo.tv"),
  "Fubo TV":                G("fubo.tv"),
  "Philo":                  G("philo.com"),
  "WatchFree+":             G("vizio.com"),
  "Haystack":               G("haystack.tv"),
  "Frndly TV":              G("frndlytv.com"),
  "Xumo":                   G("xumo.com"),
  "Plex":                   G("plex.tv"),
  "Crackle":                G("crackle.com"),
  "Tubi TV":                G("tubi.tv"),
  "YouTube TV":             G("tv.youtube.com"),
  "YouTube":                G("youtube.com"),

  // ── News Networks ────────────────────────────────────────────────────────
  "Fox News":               G("foxnews.com"),
  "CNN":                    G("cnn.com"),
  "MSNBC":                  G("msnbc.com"),
  "NewsNation":             G("newsnation.com"),
  "CNBC":                   G("cnbc.com"),
  "Fox Business":           G("foxbusiness.com"),
  "Fox Business Network":   G("foxbusiness.com"),
  "Bloomberg TV":           G("bloomberg.com"),
  "Bloomberg":              G("bloomberg.com"),
  "The Weather Channel":    G("weather.com"),
  "Weather Channel":        G("weather.com"),
  "Court TV":               G("courttv.com"),
  "Newsmax":                G("newsmax.com"),
  "OAN":                    G("oann.com"),
  "One America News":       G("oann.com"),
  "HLN":                    G("hlntv.com"),
  "C-SPAN":                 G("c-span.org"),
  "BBC News":               G("bbc.com"),
  "Al Jazeera":             G("aljazeera.com"),
  "KOTV News on 6":         G("newson6.com"),
  "KOTV":                   G("newson6.com"),
  "News on 6":              G("newson6.com"),
  "KJRH":                   G("kjrh.com"),
  "KTUL":                   G("ktul.com"),
  "KOKI":                   G("fox23.com"),

  // ── Sports ───────────────────────────────────────────────────────────────
  "ESPN":                   G("espn.com"),
  "ESPN2":                  G("espn.com"),
  "ESPNU":                  G("espn.com"),
  "ESPN+":                  G("espnplus.com"),
  "Golf Channel":           G("golfchannel.com"),
  "NFL Network":            G("nfl.com"),
  "NFL RedZone":            G("nfl.com"),
  "CBS Sports":             G("cbssports.com"),
  "CBS Sports Network":     G("cbssports.com"),
  "FS1":                    G("foxsports.com"),
  "FS2":                    G("foxsports.com"),
  "Fox Sports":             G("foxsports.com"),
  "Fox Sports 1":           G("foxsports.com"),
  "Fox Sports 2":           G("foxsports.com"),
  "NBC Sports":             G("nbcsports.com"),
  "MLB Network":            G("mlb.com"),
  "NBA TV":                 G("nba.com"),
  "Tennis Channel":         G("tennischannel.com"),
  "NHL Network":            G("nhl.com"),
  "SEC Network":            G("espn.com"),
  "ACC Network":            G("espn.com"),
  "Big Ten Network":        G("btn.com"),
  "Pac-12 Network":         G("pac-12.com"),
  "Stadium":                G("watchstadium.com"),
  "FloSports":              G("flosports.tv"),
  "DAZN":                   G("dazn.com"),
  "beIN Sports":            G("beinsports.com"),
  "Univision Deportes":     G("univision.com"),

  // ── Entertainment / Lifestyle ────────────────────────────────────────────
  "HGTV":                   G("hgtv.com"),
  "Food Network":           G("foodnetwork.com"),
  "TLC":                    G("tlc.com"),
  "Hallmark Channel":       G("hallmarkchannel.com"),
  "Hallmark Movies & Mysteries": G("hallmarkchannel.com"),
  "Lifetime":               G("mylifetime.com"),
  "A&E":                    G("aetv.com"),
  "History Channel":        G("history.com"),
  "HISTORY":                G("history.com"),
  "History":                G("history.com"),
  "Discovery Channel":      G("discovery.com"),
  "Discovery":              G("discovery.com"),
  "National Geographic":    G("nationalgeographic.com"),
  "Nat Geo":                G("nationalgeographic.com"),
  "Nat Geo Wild":           G("nationalgeographic.com"),
  "Animal Planet":          G("animalplanet.com"),
  "Bravo":                  G("bravotv.com"),
  "E! Entertainment":       G("eonline.com"),
  "E!":                     G("eonline.com"),
  "Comedy Central":         G("cc.com"),
  "MTV":                    G("mtv.com"),
  "VH1":                    G("vh1.com"),
  "BET":                    G("bet.com"),
  "BET+":                   G("bet.com"),
  "OWN":                    G("oprah.com"),
  "Oxygen":                 G("oxygen.com"),
  "Syfy":                   G("syfy.com"),
  "USA Network":            G("usanetwork.com"),
  "USA":                    G("usanetwork.com"),
  "TNT":                    G("tntdrama.com"),
  "TBS":                    G("tbs.com"),
  "AMC":                    G("amc.com"),
  "AMC+":                   G("amc.com"),
  "FX":                     G("fxnetworks.com"),
  "FXX":                    G("fxnetworks.com"),
  "FXM":                    G("fxnetworks.com"),
  "Travel Channel":         G("travelchannel.com"),
  "Cooking Channel":        G("cookingchanneltv.com"),
  "Investigation Discovery": G("investigationdiscovery.com"),
  "ID":                     G("investigationdiscovery.com"),
  "Magnolia Network":       G("magnolia.com"),
  "Tastemade":              G("tastemade.com"),
  "Nickelodeon":            G("nick.com"),
  "Nick Jr.":               G("nickjr.com"),
  "Cartoon Network":        G("cartoonnetwork.com"),
  "Disney Channel":         G("disneychannel.com"),
  "Disney XD":              G("disneyxd.com"),
  "Freeform":               G("freeform.com"),
  "Adult Swim":             G("adultswim.com"),
  "Boomerang":              G("boomerang.com"),
  "PBS Kids":               G("pbskids.org"),
  "Starz":                  G("starz.com"),
  "Showtime":               G("showtime.com"),
  "Cinemax":                G("cinemax.com"),
  "Epix":                   G("mgmplus.com"),
  "MGM+":                   G("mgmplus.com"),
  "IFC":                    G("ifcfilms.com"),
  "Sundance TV":            G("sundancetv.com"),
  "WE tv":                  G("wetv.com"),
  "Pop TV":                 G("poptv.com"),
  "Reelz":                  G("reelz.com"),
  "Fuse":                   G("fuse.tv"),
  "CuriosityStream":        G("curiositystream.com"),
  "Acorn TV":               G("acorn.tv"),
  "BritBox":                G("britbox.com"),
  "Shudder":                G("shudder.com"),
  "MotorTrend":             G("motortrend.com"),
  "Outdoor Channel":        G("outdoorchannel.com"),
  "Sportsman Channel":      G("thesportsmanchannel.com"),
  "INSP":                   G("insp.com"),
  "UPtv":                   G("uptv.com"),
  "Great American Family":  G("greatamericanfamily.com"),
  "Pure Flix":              G("pureflix.com"),
  "MeTV":                   G("metv.com"),
  "Comet":                  G("cometv.com"),
  "Grit TV":                G("grit.tv"),
  "Heroes & Icons":         G("heroesandiconstv.com"),
  "Antenna TV":             G("antennatv.tv"),
  "Laff":                   G("laffmob.com"),
  "Decades":                G("decadestv.com"),
  "Start TV":               G("startv.com"),
  "True Crime Network":     G("truecrimenetwork.com"),
  "Justice Network":        G("justicenetwork.com"),
  "Crime + Investigation":  G("crimeandinvestigation.com"),
  "Vix+":                   G("vix.com"),
  "ViX":                    G("vix.com"),
  "Univision":              G("univision.com"),
  "Telemundo":              G("telemundo.com"),
  "Estrella TV":            G("estrellatv.com"),

  // ── Game Shows ───────────────────────────────────────────────────────────
  "GSN":                    G("gsntv.com"),
  "Game Show Network":      G("gsntv.com"),

  // ── Broadcast ────────────────────────────────────────────────────────────
  "ABC":                    G("abc.com"),
  "NBC":                    G("nbc.com"),
  "CBS":                    G("cbs.com"),
  "FOX":                    G("fox.com"),
  "PBS":                    G("pbs.org"),
  "CW":                     G("cwtv.com"),
  "The CW":                 G("cwtv.com"),
  "ION":                    G("iontelevision.com"),
  "ION Television":         G("iontelevision.com"),
  "Bounce TV":              G("bouncetv.com"),
  "MyNetworkTV":            G("mynetworktv.com"),
};

/**
 * Returns the logo URL for a given network name, or null if it should use initials.
 */
export function getNetworkLogo(name: string): string | null {
  if (INITIALS_ONLY.has(name)) return null;
  return NETWORK_LOGOS[name] ?? null;
}

/**
 * Returns 1–3 uppercase initials for a network name (used for the initials badge fallback).
 */
export function getNetworkInitials(name: string): string {
  const words = name.replace(/[^a-zA-Z0-9\s+]/g, "").trim().split(/\s+/);
  if (words.length === 1) return words[0].substring(0, 3).toUpperCase();
  if (words.length === 2) return (words[0][0] + words[1][0]).toUpperCase();
  return (words[0][0] + words[1][0] + words[2][0]).toUpperCase();
}
