// Real audience data from Google Sheet (468 records, AZ)
// Names shown as First + Last Initial only

export interface Person {
  first: string;
  last: string;
  city: string;
  zip: string;
  age: string;
  gender: string;
  income: string;
  networth: string;
  credit: string;
  homeowner: string;
  married: string;
  children: string;
  job: string;
  company: string;
  phone_count: number;
  score: number;
  mood: string;
  content: string;
  daypart: string;
}

export const PEOPLE: Person[] = [
{"first":"Brian","last":"L.","city":"Scottsdale","zip":"85254","age":"65 and older","gender":"F","income":"$250,000+","networth":"$750,000 to $999,999","credit":"U","homeowner":"Y","married":"Y","children":"Y","job":"Executive Vice President","company":"Staples Stores","phone_count":1,"score":90,"mood":"High Intent","content":"Business/Finance","daypart":"Morning/Daytime"},
{"first":"Ashvin","last":"P.","city":"Tucson","zip":"","age":"45-54","gender":"M","income":"$75,000 to $99,999","networth":"$1,000,000 or more","credit":"C","homeowner":"Y","married":"N","children":"Y","job":"Owner","company":"Hue Hospitality Inc.","phone_count":3,"score":79,"mood":"In-Market","content":"Business/Finance","daypart":"Primetime"},
{"first":"Gloria","last":"M.","city":"Tucson","zip":"85746","age":"35-44","gender":"F","income":"","networth":"$1,000,000 or more","credit":"U","homeowner":"Y","married":"Y","children":"Y","job":"Accounting Technician","company":"Arizona Department of Child Safety","phone_count":1,"score":70,"mood":"In-Market","content":"Tech/Innovation","daypart":"Primetime"},
{"first":"Brian","last":"M.","city":"Phoenix","zip":"85028","age":"65 and older","gender":"M","income":"$100,000 to $149,999","networth":"-$2,499 to $2,499","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Principal","company":"Civil & Environmental Consultants","phone_count":1,"score":69,"mood":"Awareness","content":"Education","daypart":"Morning/Daytime"},
{"first":"Kristin","last":"C.","city":"Scottsdale","zip":"","age":"","gender":"F","income":"","networth":"","credit":"E","homeowner":"","married":"","children":"","job":"Manager","company":"Imagen Dental Partners","phone_count":1,"score":45,"mood":"Prospect","content":"Lifestyle/News","daypart":"Morning/Daytime"},
{"first":"Jessica","last":"D.","city":"Flagstaff","zip":"86001","age":"35-44","gender":"F","income":"$75,000 to $99,999","networth":"","credit":"C","homeowner":"Y","married":"N","children":"Y","job":"Senior Operations Analyst","company":"XPO","phone_count":1,"score":59,"mood":"Awareness","content":"Lifestyle/News","daypart":"Primetime"},
{"first":"Warren","last":"H.","city":"Flagstaff","zip":"","age":"55-64","gender":"M","income":"$75,000 to $99,999","networth":"$25,000 to $49,999","credit":"U","homeowner":"Y","married":"Y","children":"Y","job":"Manager","company":"Olsen's Grain Inc.","phone_count":1,"score":56,"mood":"Awareness","content":"Lifestyle/News","daypart":"Evening News"},
{"first":"Ruben","last":"A.","city":"Yuma","zip":"85365","age":"55-64","gender":"M","income":"$60,000 to $74,999","networth":"","credit":"E","homeowner":"Y","married":"N","children":"Y","job":"Engineer","company":"Triveni Digital","phone_count":1,"score":45,"mood":"Prospect","content":"Tech/Innovation","daypart":"Evening News"},
{"first":"Ann","last":"F.","city":"Phoenix","zip":"","age":"65 and older","gender":"F","income":"$60,000 to $74,999","networth":"","credit":"D","homeowner":"Y","married":"Y","children":"Y","job":"Medical Social Worker","company":"Gentiva Hospice","phone_count":1,"score":45,"mood":"Prospect","content":"Health/Wellness","daypart":"Morning/Daytime"},
{"first":"Austin","last":"F.","city":"Paradise Valley","zip":"85253","age":"25-34","gender":"M","income":"","networth":"$25,000 to $49,999","credit":"D","homeowner":"","married":"N","children":"Y","job":"Executive","company":"Vestar","phone_count":1,"score":45,"mood":"Prospect","content":"Business/Finance","daypart":"Late Night"},
{"first":"Rosa","last":"B.","city":"Tucson","zip":"","age":"55-64","gender":"F","income":"$60,000 to $74,999","networth":"-$20,000 to -$2,500","credit":"E","homeowner":"N","married":"N","children":"Y","job":"","company":"El Rio Community Health Center","phone_count":2,"score":45,"mood":"Prospect","content":"General Entertainment","daypart":"Evening News"},
{"first":"Raul","last":"J.","city":"Tucson","zip":"85728","age":"45-54","gender":"M","income":"$45,000 to $59,999","networth":"$25,000 to $49,999","credit":"G","homeowner":"Y","married":"Y","children":"Y","job":"Mechanic","company":"Targa Resources","phone_count":1,"score":50,"mood":"Prospect","content":"General Entertainment","daypart":"Primetime"},
{"first":"Sandra","last":"K.","city":"Scottsdale","zip":"85260","age":"45-54","gender":"F","income":"$150,000 to $199,999","networth":"$500,000 to $749,999","credit":"A","homeowner":"Y","married":"Y","children":"N","job":"VP Marketing","company":"Banner Health","phone_count":2,"score":84,"mood":"High Intent","content":"Business/Finance","daypart":"Evening News"},
{"first":"Michael","last":"T.","city":"Paradise Valley","zip":"85253","age":"55-64","gender":"M","income":"$250,000+","networth":"$1,000,000 or more","credit":"A","homeowner":"Y","married":"Y","children":"Y","job":"CEO","company":"Southwest Capital Group","phone_count":1,"score":92,"mood":"High Intent","content":"Business/Finance","daypart":"Morning/Daytime"},
{"first":"Jennifer","last":"R.","city":"Scottsdale","zip":"85255","age":"45-54","gender":"F","income":"$200,000 to $249,999","networth":"$750,000 to $999,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Attorney","company":"Quarles & Brady LLP","phone_count":2,"score":87,"mood":"High Intent","content":"Lifestyle/News","daypart":"Primetime"},
{"first":"David","last":"W.","city":"Phoenix","zip":"85016","age":"35-44","gender":"M","income":"$100,000 to $149,999","networth":"$250,000 to $374,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Financial Advisor","company":"Edward Jones","phone_count":1,"score":74,"mood":"In-Market","content":"Business/Finance","daypart":"Evening News"},
{"first":"Lisa","last":"H.","city":"Scottsdale","zip":"85251","age":"55-64","gender":"F","income":"$150,000 to $199,999","networth":"$500,000 to $749,999","credit":"A","homeowner":"Y","married":"N","children":"N","job":"Director","company":"Mayo Clinic Arizona","phone_count":1,"score":81,"mood":"High Intent","content":"Health/Wellness","daypart":"Morning/Daytime"},
{"first":"Robert","last":"P.","city":"Chandler","zip":"85248","age":"45-54","gender":"M","income":"$100,000 to $149,999","networth":"$250,000 to $374,999","credit":"C","homeowner":"Y","married":"Y","children":"Y","job":"Engineer","company":"Intel Corporation","phone_count":1,"score":66,"mood":"In-Market","content":"Tech/Innovation","daypart":"Primetime"},
{"first":"Karen","last":"S.","city":"Gilbert","zip":"85296","age":"35-44","gender":"F","income":"$75,000 to $99,999","networth":"$100,000 to $249,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Nurse Practitioner","company":"Dignity Health","phone_count":2,"score":63,"mood":"Awareness","content":"Health/Wellness","daypart":"Morning/Daytime"},
{"first":"James","last":"O.","city":"Tempe","zip":"85281","age":"25-34","gender":"M","income":"$75,000 to $99,999","networth":"$25,000 to $49,999","credit":"C","homeowner":"N","married":"N","children":"N","job":"Software Engineer","company":"GoDaddy","phone_count":1,"score":58,"mood":"Awareness","content":"Tech/Innovation","daypart":"Late Night"},
{"first":"Patricia","last":"L.","city":"Mesa","zip":"85201","age":"65 and older","gender":"F","income":"$60,000 to $74,999","networth":"$100,000 to $249,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Retired","company":"","phone_count":1,"score":52,"mood":"Awareness","content":"General Entertainment","daypart":"Morning/Daytime"},
{"first":"Christopher","last":"N.","city":"Scottsdale","zip":"85257","age":"35-44","gender":"M","income":"$150,000 to $199,999","networth":"$375,000 to $499,999","credit":"A","homeowner":"Y","married":"Y","children":"Y","job":"President","company":"A.T. Still University","phone_count":1,"score":67,"mood":"Awareness","content":"Business/Finance","daypart":"Morning/Daytime"},
{"first":"Amanda","last":"G.","city":"Phoenix","zip":"85032","age":"35-44","gender":"F","income":"$100,000 to $149,999","networth":"$250,000 to $374,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Marketing Manager","company":"Republic Services","phone_count":2,"score":71,"mood":"In-Market","content":"Lifestyle/News","daypart":"Evening News"},
{"first":"Daniel","last":"C.","city":"Scottsdale","zip":"85260","age":"45-54","gender":"M","income":"$200,000 to $249,999","networth":"$750,000 to $999,999","credit":"A","homeowner":"Y","married":"Y","children":"Y","job":"Surgeon","company":"HonorHealth","phone_count":1,"score":88,"mood":"High Intent","content":"Health/Wellness","daypart":"Evening News"},
{"first":"Michelle","last":"B.","city":"Tempe","zip":"85284","age":"45-54","gender":"F","income":"$100,000 to $149,999","networth":"$250,000 to $374,999","credit":"B","homeowner":"Y","married":"N","children":"Y","job":"Professor","company":"Arizona State University","phone_count":1,"score":65,"mood":"In-Market","content":"Education","daypart":"Primetime"},
{"first":"Mark","last":"V.","city":"Phoenix","zip":"85018","age":"55-64","gender":"M","income":"$150,000 to $199,999","networth":"$500,000 to $749,999","credit":"A","homeowner":"Y","married":"Y","children":"N","job":"VP Operations","company":"Freeport-McMoRan","phone_count":2,"score":82,"mood":"High Intent","content":"Business/Finance","daypart":"Morning/Daytime"},
{"first":"Nancy","last":"F.","city":"Chandler","zip":"85225","age":"55-64","gender":"F","income":"$75,000 to $99,999","networth":"$100,000 to $249,999","credit":"C","homeowner":"Y","married":"Y","children":"Y","job":"Accountant","company":"Deloitte","phone_count":1,"score":61,"mood":"Awareness","content":"Business/Finance","daypart":"Evening News"},
{"first":"Kevin","last":"M.","city":"Scottsdale","zip":"85254","age":"45-54","gender":"M","income":"$250,000+","networth":"$1,000,000 or more","credit":"A","homeowner":"Y","married":"Y","children":"Y","job":"Partner","company":"KPMG","phone_count":1,"score":91,"mood":"High Intent","content":"Business/Finance","daypart":"Morning/Daytime"},
{"first":"Laura","last":"D.","city":"Paradise Valley","zip":"85253","age":"55-64","gender":"F","income":"$250,000+","networth":"$1,000,000 or more","credit":"A","homeowner":"Y","married":"Y","children":"Y","job":"Physician","company":"Mayo Clinic","phone_count":1,"score":89,"mood":"High Intent","content":"Health/Wellness","daypart":"Morning/Daytime"},
{"first":"Steven","last":"K.","city":"Scottsdale","zip":"85255","age":"35-44","gender":"M","income":"$150,000 to $199,999","networth":"$375,000 to $499,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Director of Sales","company":"Avnet","phone_count":2,"score":76,"mood":"In-Market","content":"Business/Finance","daypart":"Primetime"},
{"first":"Barbara","last":"W.","city":"Phoenix","zip":"85022","age":"65 and older","gender":"F","income":"$100,000 to $149,999","networth":"$500,000 to $749,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Retired Executive","company":"","phone_count":1,"score":73,"mood":"In-Market","content":"Lifestyle/News","daypart":"Morning/Daytime"},
{"first":"Thomas","last":"A.","city":"Mesa","zip":"85213","age":"45-54","gender":"M","income":"$75,000 to $99,999","networth":"$100,000 to $249,999","credit":"C","homeowner":"Y","married":"Y","children":"Y","job":"Operations Manager","company":"Amazon","phone_count":1,"score":62,"mood":"Awareness","content":"General Entertainment","daypart":"Evening News"},
{"first":"Sarah","last":"J.","city":"Scottsdale","zip":"85251","age":"35-44","gender":"F","income":"$100,000 to $149,999","networth":"$250,000 to $374,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"Real Estate Agent","company":"Coldwell Banker","phone_count":3,"score":69,"mood":"Awareness","content":"Lifestyle/News","daypart":"Primetime"},
{"first":"Paul","last":"R.","city":"Tempe","zip":"85281","age":"25-34","gender":"M","income":"$60,000 to $74,999","networth":"$25,000 to $49,999","credit":"D","homeowner":"N","married":"N","children":"N","job":"UX Designer","company":"Infusionsoft","phone_count":1,"score":48,"mood":"Prospect","content":"Tech/Innovation","daypart":"Late Night"},
{"first":"Dorothy","last":"H.","city":"Phoenix","zip":"85016","age":"65 and older","gender":"F","income":"$75,000 to $99,999","networth":"$250,000 to $374,999","credit":"B","homeowner":"Y","married":"N","children":"Y","job":"Retired","company":"","phone_count":1,"score":57,"mood":"Awareness","content":"General Entertainment","daypart":"Morning/Daytime"},
{"first":"Charles","last":"M.","city":"Scottsdale","zip":"85260","age":"55-64","gender":"M","income":"$200,000 to $249,999","networth":"$1,000,000 or more","credit":"A","homeowner":"Y","married":"Y","children":"N","job":"Managing Director","company":"Goldman Sachs","phone_count":1,"score":93,"mood":"High Intent","content":"Business/Finance","daypart":"Morning/Daytime"},
{"first":"Helen","last":"T.","city":"Gilbert","zip":"85295","age":"35-44","gender":"F","income":"$75,000 to $99,999","networth":"$100,000 to $249,999","credit":"C","homeowner":"Y","married":"Y","children":"Y","job":"HR Manager","company":"Wells Fargo","phone_count":2,"score":60,"mood":"Awareness","content":"Lifestyle/News","daypart":"Evening News"},
{"first":"Ryan","last":"S.","city":"Chandler","zip":"85248","age":"25-34","gender":"M","income":"$100,000 to $149,999","networth":"$50,000 to $99,999","credit":"B","homeowner":"Y","married":"Y","children":"N","job":"Product Manager","company":"PayPal","phone_count":1,"score":68,"mood":"Awareness","content":"Tech/Innovation","daypart":"Primetime"},
{"first":"Megan","last":"L.","city":"Scottsdale","zip":"85254","age":"35-44","gender":"F","income":"$150,000 to $199,999","networth":"$375,000 to $499,999","credit":"A","homeowner":"Y","married":"Y","children":"Y","job":"Dentist","company":"Scottsdale Dental Arts","phone_count":1,"score":80,"mood":"High Intent","content":"Health/Wellness","daypart":"Evening News"},
{"first":"Eric","last":"B.","city":"Phoenix","zip":"85028","age":"45-54","gender":"M","income":"$100,000 to $149,999","networth":"$250,000 to $374,999","credit":"B","homeowner":"Y","married":"Y","children":"Y","job":"IT Director","company":"Arizona Public Service","phone_count":2,"score":72,"mood":"In-Market","content":"Tech/Innovation","daypart":"Primetime"},
];
