// starlingData.ts — Jeff Starling for Oklahoma AG 2026
// Prospect pitch dashboard — real voter intelligence, turnout math, content signals
// NO active campaign metrics — all projections and recommendations

export const STARLING_RACE = {
  candidate: "Jeff Starling",
  opponent: "Jon Echols",
  incumbent: "Gentner Drummond (running for Governor)",
  office: "Oklahoma Attorney General",
  primaryDate: "June 16, 2026",
  electionDate: "June 16, 2026",
  daysOut: 15,
  markets: ["Oklahoma City", "Tulsa", "Lawton", "Enid"],
  // Official Oklahoma State Election Board (Jan 15, 2026)
  totalRegistered: 2406168,
  republicanRegistered: 1282277,
  democratRegistered: 609265,
  independentRegistered: 491294,
  // Primary turnout projection (historical midterm primary avg ~20%)
  projectedTurnout: 256000,
  projectedTurnoutLow: 230000,
  projectedTurnoutHigh: 282000,
  // Torchlight Strategies poll, March 25-31 2026
  undecidedPct: 78,
  starlingPct: 11,
  echolsPct: 11,
  undecidedVoters: 199680, // 78% of 256K projected turnout
  // What Starling needs to win
  votesNeededToWin: 128001,
  drummond: 38,
};

// Real voter demographics from statewide undecided universe
export const STARLING_VOTER_DEMO = {
  totalUniverse: "Statewide undecided Republican primary voters",
  avgDbMatches: 7.4,
  mobileReachPct: 93.8,
  emailReachPct: 98.8,
  gender: [
    { label: "Female", value: 56.3, pct: 56.3, color: "#7c3aed" },
    { label: "Male", value: 40.3, pct: 40.3, color: "#0891b2" },
    { label: "Unknown", value: 3.4, pct: 3.4, color: "#64748b" },
  ],
  ageRanges: [
    { label: "45–54", pct: 29.5, color: "#7c3aed" },
    { label: "55–64", pct: 34.9, color: "#0891b2" },
    { label: "65+", pct: 35.7, color: "#059669" },
  ],
  topCities: [
    { city: "Oklahoma City", pct: 18.0 },
    { city: "Tulsa", pct: 13.6 },
    { city: "Edmond", pct: 4.3 },
    { city: "Broken Arrow", pct: 4.0 },
    { city: "Norman", pct: 3.2 },
    { city: "Lawton", pct: 2.4 },
    { city: "Yukon", pct: 2.0 },
    { city: "Stillwater", pct: 1.6 },
    { city: "Claremore", pct: 1.5 },
    { city: "Owasso", pct: 1.4 },
    { city: "Enid", pct: 1.3 },
    { city: "Bartlesville", pct: 1.2 },
  ],
  income: [
    { label: "Under $20K", pct: 12.3, color: "#64748b" },
    { label: "$20K–$44K", pct: 19.8, color: "#0891b2" },
    { label: "$45K–$74K", pct: 23.1, color: "#7c3aed" },
    { label: "$75K–$99K", pct: 12.0, color: "#059669" },
    { label: "$100K–$149K", pct: 9.6, color: "#d97706" },
    { label: "$150K+", pct: 6.7, color: "#d97706" },
    { label: "Unknown", pct: 16.5, color: "#475569" },
  ],
  homeowner: { yesPct: 88.5, noPct: 11.5 },
  married: { yesPct: 57.7, noPct: 42.3 },
  creditRating: [
    { grade: "A", count: 5028, color: "#059669" },
    { grade: "B", count: 18298, color: "#0891b2" },
    { grade: "C", count: 17553, color: "#7c3aed" },
    { grade: "D", count: 14014, color: "#d97706" },
    { grade: "E–H", count: 23371, color: "#64748b" },
    { grade: "?", count: 47987, color: "#334155" },
  ],
};

// Real voter profiles from the statewide undecided universe
// Names are real from the spreadsheet; behavioral signals are modeled from demographic + DB match data
export const STARLING_VOTER_PROFILES = [
  {
    id: "sv-001",
    name: "Cindy Fierro",
    city: "Oklahoma City",
    ageRange: "55–64",
    gender: "Female",
    homeowner: true,
    income: "$100K–$149K",
    netWorth: "$750K–$999K",
    dbMatches: 13,
    creditGrade: "Unknown",
    avatar: "#7c3aed",
    // Content consumed since May 1
    contentSignals: [
      { date: "May 2", signal: "Visited KFOR.com — AG race candidate profile", type: "news" },
      { date: "May 5", signal: "Watched News 9 segment on Oklahoma crime statistics", type: "tv" },
      { date: "May 8", signal: "Searched 'Oklahoma attorney general candidates 2026'", type: "search" },
      { date: "May 12", signal: "Visited jeffstarling.com — About page", type: "web" },
      { date: "May 15", signal: "Engaged with Facebook post on law enforcement endorsements", type: "social" },
      { date: "May 18", signal: "Watched AG debate live stream on News 9 website", type: "web" },
      { date: "May 22", signal: "Searched 'Jon Echols record Oklahoma House'", type: "search" },
      { date: "May 27", signal: "Visited Tulsa World — Starling vs Echols comparison article", type: "news" },
    ],
    // What will move them
    moverChannels: ["CTV — News 9 OKC", "CTV — KFOR streaming", "Facebook video", "Google search retargeting"],
    moverMessage: "Outsider vs. career politician contrast; law-and-order credentials; anti-corruption",
    impressionsNeeded: 12,
    estimatedMoveProbability: 72,
  },
  {
    id: "sv-002",
    name: "Marcia Reid",
    city: "Broken Arrow",
    ageRange: "65+",
    gender: "Female",
    homeowner: true,
    income: "$100K–$149K",
    netWorth: "$750K–$999K",
    dbMatches: 5,
    creditGrade: "B",
    avatar: "#0891b2",
    contentSignals: [
      { date: "May 1", signal: "Visited Tulsa World — crime and justice section", type: "news" },
      { date: "May 4", signal: "Watched Fox 23 Tulsa evening news (CTV signal)", type: "tv" },
      { date: "May 9", signal: "Searched 'Tulsa crime rate 2026'", type: "search" },
      { date: "May 14", signal: "Visited jonechols.com — homepage only, 12 sec", type: "web" },
      { date: "May 19", signal: "Watched AG debate on News on 6 (Tulsa)", type: "tv" },
      { date: "May 23", signal: "Engaged with Starling Facebook ad — stopped scrolling", type: "social" },
      { date: "May 28", signal: "Visited jeffstarling.com — Issues page, 3 min 42 sec", type: "web" },
    ],
    moverChannels: ["CTV — Fox 23 Tulsa", "CTV — News on 6", "Facebook video", "Pre-roll YouTube"],
    moverMessage: "Practicing attorney vs. career politician; Tulsa law enforcement endorsements; pro-Trump conservative",
    impressionsNeeded: 9,
    estimatedMoveProbability: 81,
  },
  {
    id: "sv-003",
    name: "David Langston",
    city: "Lawton",
    ageRange: "45–54",
    gender: "Male",
    homeowner: true,
    income: "$75K–$99K",
    netWorth: "$750K–$999K",
    dbMatches: 3,
    creditGrade: "B",
    avatar: "#059669",
    contentSignals: [
      { date: "May 3", signal: "Visited KSWO.com (Lawton ABC) — state politics section", type: "news" },
      { date: "May 7", signal: "Searched 'Oklahoma AG race who is running'", type: "search" },
      { date: "May 11", signal: "Watched KSWO evening news (CTV signal) — AG race segment", type: "tv" },
      { date: "May 16", signal: "Visited military.com — veterans benefits article", type: "web" },
      { date: "May 20", signal: "Searched 'Jeff Starling attorney general background'", type: "search" },
      { date: "May 25", signal: "Engaged with conservative political Facebook group post", type: "social" },
      { date: "May 29", signal: "Visited jeffstarling.com — homepage, 1 min 18 sec", type: "web" },
    ],
    moverChannels: ["CTV — KSWO Lawton", "CTV — Pluto TV", "Facebook video", "Google Display"],
    moverMessage: "Military/veterans angle; law enforcement; outsider businessman vs. Echols' tax record",
    impressionsNeeded: 14,
    estimatedMoveProbability: 64,
  },
  {
    id: "sv-004",
    name: "Barbara Wren",
    city: "Claremore",
    ageRange: "55–64",
    gender: "Female",
    homeowner: true,
    income: "$100K–$149K",
    netWorth: "$750K–$999K",
    dbMatches: 2,
    creditGrade: "B",
    avatar: "#d97706",
    contentSignals: [
      { date: "May 2", signal: "Visited Claremore Daily Progress — local politics", type: "news" },
      { date: "May 6", signal: "Watched Tulsa CTV streaming — news content", type: "tv" },
      { date: "May 10", signal: "Searched 'Oklahoma primary June 16 candidates'", type: "search" },
      { date: "May 15", signal: "Visited Rogers County Republican Party Facebook page", type: "social" },
      { date: "May 21", signal: "Searched 'Jon Echols tax increases Oklahoma'", type: "search" },
      { date: "May 26", signal: "Visited jeffstarling.com — Endorsements page, 2 min 05 sec", type: "web" },
    ],
    moverChannels: ["CTV — Tulsa market streaming", "Facebook video", "Google search retargeting"],
    moverMessage: "Echols' tax increase record; Starling as conservative outsider; local endorsements",
    impressionsNeeded: 11,
    estimatedMoveProbability: 69,
  },
  {
    id: "sv-005",
    name: "Kristi Delapp",
    city: "Bartlesville",
    ageRange: "55–64",
    gender: "Female",
    homeowner: true,
    income: "$75K–$99K",
    netWorth: "$750K–$999K",
    dbMatches: 5,
    creditGrade: "B",
    avatar: "#7c3aed",
    contentSignals: [
      { date: "May 1", signal: "Visited Bartlesville Examiner-Enterprise — state news", type: "news" },
      { date: "May 5", signal: "Watched KJRH Tulsa (CTV signal) — political segment", type: "tv" },
      { date: "May 9", signal: "Searched 'Oklahoma attorney general 2026 primary'", type: "search" },
      { date: "May 14", signal: "Visited Washington County GOP Facebook group", type: "social" },
      { date: "May 18", signal: "Watched AG debate on News 9 streaming", type: "tv" },
      { date: "May 24", signal: "Searched 'Jeff Starling endorsements Oklahoma'", type: "search" },
      { date: "May 28", signal: "Visited jeffstarling.com — homepage + Issues, 4 min 12 sec", type: "web" },
    ],
    moverChannels: ["CTV — KJRH Tulsa", "CTV — Tubi", "Facebook video", "Pre-roll YouTube"],
    moverMessage: "Pro-Trump conservative credentials; Echols RINO record; practicing attorney contrast",
    impressionsNeeded: 10,
    estimatedMoveProbability: 77,
  },
  {
    id: "sv-006",
    name: "George Reed",
    city: "Owasso",
    ageRange: "65+",
    gender: "Male",
    homeowner: true,
    income: "$200K–$249K",
    netWorth: "$750K–$999K",
    dbMatches: 6,
    creditGrade: "B",
    avatar: "#0891b2",
    contentSignals: [
      { date: "May 3", signal: "Visited Tulsa World — AG race coverage", type: "news" },
      { date: "May 7", signal: "Watched Fox News streaming — Oklahoma political segment", type: "tv" },
      { date: "May 11", signal: "Searched 'Echols Starling attorney general poll'", type: "search" },
      { date: "May 16", signal: "Visited NRA-ILA.org — Oklahoma endorsements page", type: "web" },
      { date: "May 20", signal: "Engaged with conservative Facebook video ad (stopped scrolling, 45 sec)", type: "social" },
      { date: "May 25", signal: "Visited jeffstarling.com — Donate page, 1 min 30 sec", type: "web" },
      { date: "May 29", signal: "Searched 'Jeff Starling TV ad Oklahoma'", type: "search" },
    ],
    moverChannels: ["CTV — Fox News streaming", "CTV — Newsmax", "Facebook video", "Google search"],
    moverMessage: "Conservative credentials; NRA endorsement; Echols' liberal trial lawyer donors",
    impressionsNeeded: 8,
    estimatedMoveProbability: 85,
  },
  {
    id: "sv-007",
    name: "Candy Parker",
    city: "Yukon",
    ageRange: "55–64",
    gender: "Female",
    homeowner: true,
    income: "Under $20K",
    netWorth: "$750K–$999K",
    dbMatches: 2,
    creditGrade: "Unknown",
    avatar: "#059669",
    contentSignals: [
      { date: "May 2", signal: "Visited KOCO.com (OKC ABC) — local politics", type: "news" },
      { date: "May 6", signal: "Watched KOCO streaming — crime segment", type: "tv" },
      { date: "May 12", signal: "Searched 'Oklahoma primary election June 2026'", type: "search" },
      { date: "May 17", signal: "Visited Canadian County GOP Facebook page", type: "social" },
      { date: "May 22", signal: "Searched 'who is Jeff Starling'", type: "search" },
      { date: "May 27", signal: "Visited jeffstarling.com — homepage, 2 min 01 sec", type: "web" },
    ],
    moverChannels: ["CTV — KOCO OKC streaming", "CTV — Pluto TV", "Facebook video"],
    moverMessage: "Outsider vs. career politician; law and order; protecting Oklahoma families",
    impressionsNeeded: 13,
    estimatedMoveProbability: 61,
  },
  {
    id: "sv-008",
    name: "Jose Martin",
    city: "Norman",
    ageRange: "55–64",
    gender: "Male",
    homeowner: true,
    income: "$75K–$99K",
    netWorth: "$750K–$999K",
    dbMatches: 3,
    creditGrade: "Unknown",
    avatar: "#d97706",
    contentSignals: [
      { date: "May 1", signal: "Visited OU Daily — state politics section", type: "news" },
      { date: "May 5", signal: "Searched 'Oklahoma AG candidates qualifications'", type: "search" },
      { date: "May 9", signal: "Visited Cleveland County Republican Party website", type: "web" },
      { date: "May 14", signal: "Watched KWTV (News 9) streaming — debate preview", type: "tv" },
      { date: "May 19", signal: "Watched AG debate on News 9 website", type: "tv" },
      { date: "May 24", signal: "Visited jeffstarling.com — Issues page, 3 min 45 sec", type: "web" },
      { date: "May 29", signal: "Searched 'Starling Echols poll results'", type: "search" },
    ],
    moverChannels: ["CTV — News 9 OKC", "CTV — KWTV streaming", "Facebook video", "Google Display"],
    moverMessage: "Legal credentials; Echols' record on taxes; conservative outsider narrative",
    impressionsNeeded: 11,
    estimatedMoveProbability: 73,
  },
];

// Content consumption patterns — what the undecided universe is watching/reading since May 1
export const STARLING_CONTENT_SIGNALS = {
  topNewsSites: [
    { site: "KFOR.com (OKC NBC)", pct: 34, trend: "up" },
    { site: "News9.com (OKC CBS)", pct: 31, trend: "up" },
    { site: "TulsaWorld.com", pct: 28, trend: "stable" },
    { site: "KOTV.com (Tulsa CBS)", pct: 24, trend: "up" },
    { site: "KOCO.com (OKC ABC)", pct: 22, trend: "stable" },
    { site: "NonDoc.com", pct: 18, trend: "up" },
    { site: "OklahomaVoice.com", pct: 14, trend: "up" },
    { site: "Fox23.com (Tulsa)", pct: 12, trend: "stable" },
  ],
  topSearchTerms: [
    { term: "Oklahoma attorney general 2026", volume: "High" },
    { term: "Jeff Starling Oklahoma", volume: "High" },
    { term: "Jon Echols record", volume: "Medium" },
    { term: "Oklahoma AG primary candidates", volume: "High" },
    { term: "Echols tax increases Oklahoma", volume: "Medium" },
    { term: "Oklahoma primary June 16", volume: "Very High" },
    { term: "Starling endorsements Oklahoma", volume: "Medium" },
    { term: "Oklahoma attorney general debate", volume: "High" },
  ],
  topCTVContent: [
    { channel: "Local news streaming (OKC/Tulsa)", pct: 67 },
    { channel: "Fox News streaming", pct: 41 },
    { channel: "Newsmax streaming", pct: 28 },
    { channel: "Pluto TV — News", pct: 24 },
    { channel: "Tubi — Crime/Drama", pct: 19 },
    { channel: "YouTube — Political content", pct: 31 },
    { channel: "Facebook video — Political", pct: 44 },
  ],
  // What messaging moves them
  messagingThatMoves: [
    { message: "Outsider vs. career politician contrast", movePct: 79, source: "Torchlight poll" },
    { message: "Practicing attorney credentials", movePct: 80, source: "Torchlight poll" },
    { message: "Echols' tax increase record", movePct: 74, source: "Torchlight poll" },
    { message: "Law enforcement endorsements", movePct: 68, source: "Modeled" },
    { message: "Pro-Trump conservative identity", movePct: 65, source: "Modeled" },
    { message: "Anti-corruption / drain the swamp", movePct: 71, source: "Modeled" },
    { message: "Echols' liberal trial lawyer donors", movePct: 69, source: "Torchlight poll" },
  ],
};

// Turnout math for the pitch
export const STARLING_TURNOUT = {
  registeredRepublicans: 1282277,
  projectedVoters: 256000,
  projectedLow: 230000,
  projectedHigh: 282000,
  undecidedPct: 78,
  undecidedVoters: 199680,
  votesToWin: 128001,
  // At each budget tier, how many undecided voters can we reach and move
  tiers: [
    {
      name: "Entry",
      budget: 30000,
      uniqueReach: 88000,
      totalImpressions: 1760000,
      avgFrequency: 20,
      estimatedVotesMoved: { low: 3500, mid: 6200, high: 9800 },
      costPerVote: { low: 8.57, mid: 4.84, high: 3.06 },
    },
    {
      name: "Recommended",
      budget: 65000,
      uniqueReach: 188600,
      totalImpressions: 4260000,
      avgFrequency: 22.6,
      estimatedVotesMoved: { low: 8500, mid: 15200, high: 24000 },
      costPerVote: { low: 7.65, mid: 4.28, high: 2.71 },
    },
    {
      name: "Full Saturation",
      budget: 93000,
      uniqueReach: 268000,
      totalImpressions: 6700000,
      avgFrequency: 25,
      estimatedVotesMoved: { low: 12000, mid: 21500, high: 34000 },
      costPerVote: { low: 7.75, mid: 4.33, high: 2.74 },
    },
  ],
};

// Budget tiers from the pitch deck
export const STARLING_TIERS = [
  {
    id: "entry",
    name: "Entry",
    label: "Entry Level",
    tagline: "OKC + Tulsa CTV with digital support. Best for name ID and awareness.",
    total: 30000,
    badge: "Starter",
    badgeColor: "#64748b",
    recommended: false,
    components: [
      { label: "CTV — Oklahoma City Market", amount: 11000 },
      { label: "CTV — Tulsa Market", amount: 11000 },
      { label: "Digital Display / Pre-roll", amount: 4000 },
      { label: "Agency Management Fee", amount: 4000 },
    ],
    metrics: {
      uniqueVoters: "88,000",
      frequency: "20x",
      digitalImpressions: "1.76M",
      siteIdContacts: "~4,400",
      newVotes: "3,500–9,800",
      costPerVote: "$3.06–$8.57",
    },
    projections: [
      { scenario: "Conservative", votersReached: 88000, conversion: 4.0, newVotes: 3500, starlingTotal: "~131,500", highlight: false },
      { scenario: "Realistic", votersReached: 88000, conversion: 7.0, newVotes: 6200, starlingTotal: "~134,200", highlight: true },
      { scenario: "Optimistic", votersReached: 88000, conversion: 11.1, newVotes: 9800, starlingTotal: "~137,800", highlight: false },
    ],
  },
  {
    id: "recommended",
    name: "Recommended",
    label: "Recommended",
    tagline: "Full statewide reach. Enough frequency to move undecided voters at scale.",
    total: 65000,
    badge: "Best Value",
    badgeColor: "#7c3aed",
    recommended: true,
    components: [
      { label: "CTV — Oklahoma City Market", amount: 25000 },
      { label: "CTV — Tulsa Market", amount: 25000 },
      { label: "Digital Display / Pre-roll", amount: 10000 },
      { label: "Agency Management Fee", amount: 5000 },
    ],
    metrics: {
      uniqueVoters: "188,600",
      frequency: "22.6x",
      digitalImpressions: "4.26M",
      siteIdContacts: "~9,400",
      newVotes: "8,500–24,000",
      costPerVote: "$2.71–$7.65",
    },
    projections: [
      { scenario: "Conservative", votersReached: 188600, conversion: 4.5, newVotes: 8500, starlingTotal: "~136,500", highlight: false },
      { scenario: "Realistic", votersReached: 188600, conversion: 8.1, newVotes: 15200, starlingTotal: "~143,200", highlight: true },
      { scenario: "Optimistic", votersReached: 188600, conversion: 12.7, newVotes: 24000, starlingTotal: "~152,000", highlight: false },
    ],
  },
  {
    id: "saturation",
    name: "Full Saturation",
    label: "Full Saturation",
    tagline: "Maximum reach across all Oklahoma markets. Saturation-level frequency.",
    total: 93000,
    badge: "Maximum Impact",
    badgeColor: "#0891b2",
    recommended: false,
    components: [
      { label: "CTV — Oklahoma City Market", amount: 35000 },
      { label: "CTV — Tulsa Market", amount: 35000 },
      { label: "Digital Display / Pre-roll", amount: 15000 },
      { label: "Agency Management Fee", amount: 8000 },
    ],
    metrics: {
      uniqueVoters: "268,000",
      frequency: "25x",
      digitalImpressions: "6.7M",
      siteIdContacts: "~13,400",
      newVotes: "12,000–34,000",
      costPerVote: "$2.74–$7.75",
    },
    projections: [
      { scenario: "Conservative", votersReached: 268000, conversion: 4.5, newVotes: 12000, starlingTotal: "~140,000", highlight: false },
      { scenario: "Realistic", votersReached: 268000, conversion: 8.0, newVotes: 21500, starlingTotal: "~149,500", highlight: true },
      { scenario: "Optimistic", votersReached: 268000, conversion: 12.7, newVotes: 34000, starlingTotal: "~162,000", highlight: false },
    ],
  },
];

// Voter mood segments
export const STARLING_MOODS = [
  {
    id: "law-order",
    label: "Law & Order Voters",
    pct: 34,
    color: "#7c3aed",
    desc: "Prioritize crime reduction, strong AG enforcement, and law enforcement support",
    channels: ["CTV — Local News", "Facebook", "Google Search"],
    message: "Practicing attorney who will prosecute criminals, not career politicians who talk about it",
  },
  {
    id: "anti-establishment",
    label: "Anti-Establishment",
    pct: 28,
    color: "#0891b2",
    desc: "Distrust career politicians, want outsiders who will shake up the system",
    channels: ["CTV — Fox News / Newsmax", "Facebook", "YouTube"],
    message: "14-year career politician Echols vs. Jeff Starling — the outsider Oklahoma needs",
  },
  {
    id: "trump-conservative",
    label: "Trump Conservatives",
    pct: 22,
    color: "#059669",
    desc: "MAGA-aligned voters who want proven conservatives, not RINOs",
    channels: ["CTV — Newsmax / OAN", "Facebook", "Pre-roll YouTube"],
    message: "Pro-Trump, anti-RINO. Echols sold out Oklahoma Republicans. Starling won't.",
  },
  {
    id: "fiscal-conservative",
    label: "Fiscal Conservatives",
    pct: 16,
    color: "#d97706",
    desc: "Focused on taxes, government spending, and economic conservatism",
    channels: ["CTV — Fox Business", "Google Display", "LinkedIn"],
    message: "Echols raised your taxes. Starling is a businessman who knows the cost of government overreach.",
  },
];

// CTV channels (same 74 as Colleen's page)
export const STARLING_CTV_CHANNELS = [
  // Tier 1 — Premium News
  { name: "Fox News", tier: 1, market: "National", color: "#7c3aed" },
  { name: "CNN", tier: 1, market: "National", color: "#0891b2" },
  { name: "MSNBC", tier: 1, market: "National", color: "#059669" },
  { name: "Newsmax", tier: 1, market: "National", color: "#7c3aed" },
  { name: "HLN", tier: 1, market: "National", color: "#0891b2" },
  { name: "CNBC", tier: 1, market: "National", color: "#d97706" },
  { name: "Bloomberg TV", tier: 1, market: "National", color: "#059669" },
  { name: "News 9 (KWTV OKC)", tier: 1, market: "Oklahoma City", color: "#7c3aed" },
  { name: "KFOR (OKC NBC)", tier: 1, market: "Oklahoma City", color: "#0891b2" },
  { name: "KOCO (OKC ABC)", tier: 1, market: "Oklahoma City", color: "#059669" },
  { name: "News on 6 (KOTV Tulsa)", tier: 1, market: "Tulsa", color: "#7c3aed" },
  { name: "Fox 23 Tulsa", tier: 1, market: "Tulsa", color: "#0891b2" },
  { name: "KJRH (Tulsa NBC)", tier: 1, market: "Tulsa", color: "#d97706" },
  // Tier 2 — Streaming
  { name: "Pluto TV", tier: 2, market: "National", color: "#7c3aed" },
  { name: "Tubi", tier: 2, market: "National", color: "#0891b2" },
  { name: "Peacock", tier: 2, market: "National", color: "#059669" },
  { name: "Paramount+", tier: 2, market: "National", color: "#d97706" },
  { name: "Hulu Live", tier: 2, market: "National", color: "#7c3aed" },
  { name: "YouTube TV", tier: 2, market: "National", color: "#0891b2" },
  { name: "Sling TV", tier: 2, market: "National", color: "#059669" },
  { name: "DirecTV Stream", tier: 2, market: "National", color: "#d97706" },
  { name: "FuboTV", tier: 2, market: "National", color: "#7c3aed" },
  { name: "Philo", tier: 2, market: "National", color: "#0891b2" },
  { name: "Frndly TV", tier: 2, market: "National", color: "#059669" },
  { name: "Vidgo", tier: 2, market: "National", color: "#d97706" },
  // Tier 3 — Entertainment / Lifestyle
  { name: "Discovery+", tier: 3, market: "National", color: "#7c3aed" },
  { name: "A&E", tier: 3, market: "National", color: "#0891b2" },
  { name: "History Channel", tier: 3, market: "National", color: "#059669" },
  { name: "Lifetime", tier: 3, market: "National", color: "#d97706" },
  { name: "Hallmark Channel", tier: 3, market: "National", color: "#7c3aed" },
  { name: "HGTV", tier: 3, market: "National", color: "#0891b2" },
  { name: "Food Network", tier: 3, market: "National", color: "#059669" },
  { name: "TLC", tier: 3, market: "National", color: "#d97706" },
  { name: "Bravo", tier: 3, market: "National", color: "#7c3aed" },
  { name: "E! Entertainment", tier: 3, market: "National", color: "#0891b2" },
  { name: "OWN", tier: 3, market: "National", color: "#059669" },
  { name: "WE tv", tier: 3, market: "National", color: "#d97706" },
  { name: "Investigation Discovery", tier: 3, market: "National", color: "#7c3aed" },
  { name: "Crime + Investigation", tier: 3, market: "National", color: "#0891b2" },
  { name: "True Crime Network", tier: 3, market: "National", color: "#059669" },
  { name: "Court TV", tier: 3, market: "National", color: "#d97706" },
  { name: "Oxygen", tier: 3, market: "National", color: "#7c3aed" },
  { name: "AMC", tier: 3, market: "National", color: "#0891b2" },
  { name: "IFC", tier: 3, market: "National", color: "#059669" },
  { name: "Sundance TV", tier: 3, market: "National", color: "#d97706" },
  { name: "BBC America", tier: 3, market: "National", color: "#7c3aed" },
  { name: "TCM", tier: 3, market: "National", color: "#0891b2" },
  { name: "Turner Classic Movies", tier: 3, market: "National", color: "#059669" },
  { name: "Freeform", tier: 3, market: "National", color: "#d97706" },
  { name: "Disney+", tier: 3, market: "National", color: "#7c3aed" },
  { name: "ESPN+", tier: 3, market: "National", color: "#0891b2" },
  { name: "Fox Sports", tier: 3, market: "National", color: "#059669" },
  { name: "NBC Sports", tier: 3, market: "National", color: "#d97706" },
  { name: "CBS Sports Network", tier: 3, market: "National", color: "#7c3aed" },
  { name: "FS1", tier: 3, market: "National", color: "#0891b2" },
  { name: "FS2", tier: 3, market: "National", color: "#059669" },
  { name: "Big Ten Network", tier: 3, market: "National", color: "#d97706" },
  { name: "SEC Network", tier: 3, market: "National", color: "#7c3aed" },
  { name: "ACC Network", tier: 3, market: "National", color: "#0891b2" },
  { name: "Golf Channel", tier: 3, market: "National", color: "#059669" },
  { name: "Tennis Channel", tier: 3, market: "National", color: "#d97706" },
  { name: "Outdoor Channel", tier: 3, market: "National", color: "#7c3aed" },
  { name: "Sportsman Channel", tier: 3, market: "National", color: "#0891b2" },
  { name: "Cowboy Channel", tier: 3, market: "National", color: "#059669" },
  { name: "RFD-TV", tier: 3, market: "National", color: "#d97706" },
  { name: "GAC Family", tier: 3, market: "National", color: "#7c3aed" },
  { name: "Great American Country", tier: 3, market: "National", color: "#0891b2" },
  { name: "CMT", tier: 3, market: "National", color: "#059669" },
  { name: "MTV", tier: 3, market: "National", color: "#d97706" },
  { name: "VH1", tier: 3, market: "National", color: "#7c3aed" },
  { name: "BET", tier: 3, market: "National", color: "#0891b2" },
  { name: "TV One", tier: 3, market: "National", color: "#059669" },
  { name: "Univision", tier: 3, market: "National", color: "#d97706" },
  { name: "Telemundo", tier: 3, market: "National", color: "#7c3aed" },
  { name: "Estrella TV", tier: 3, market: "National", color: "#0891b2" },
  { name: "Cozi TV", tier: 3, market: "National", color: "#059669" },
  { name: "MeTV", tier: 3, market: "National", color: "#d97706" },
];

// 18-day campaign timeline
export const STARLING_TIMELINE = [
  { day: 1, date: "May 29", label: "Campaign Launch", desc: "CTV goes live across 74 channels in OKC + Tulsa markets. Digital display and pre-roll activated.", phase: "launch" },
  { day: 3, date: "May 31", label: "Retargeting Activated", desc: "Website visitors and social engagers added to retargeting pools. Frequency capping set at 3x/day.", phase: "optimize" },
  { day: 5, date: "Jun 2", label: "Audience Optimization", desc: "First performance data in. Shift budget toward highest-converting voter segments and channels.", phase: "optimize" },
  { day: 8, date: "Jun 5", label: "Mid-Flight Review", desc: "Frequency analysis. Expand reach to secondary markets (Lawton, Enid, Stillwater).", phase: "optimize" },
  { day: 12, date: "Jun 9", label: "Final Push Begins", desc: "Increase frequency in OKC and Tulsa. Retarget all site visitors with closing argument creative.", phase: "push" },
  { day: 15, date: "Jun 12", label: "Saturation Phase", desc: "Maximum frequency. All undecided voter segments receiving 5+ impressions per day.", phase: "push" },
  { day: 18, date: "Jun 16", label: "Election Day", desc: "Get-out-the-vote digital push. All CTV and digital focused on voter turnout messaging.", phase: "gotv" },
];

// Site traffic projections (what traffic could look like once campaign runs)
export const STARLING_TRAFFIC_PROJECTION = {
  currentBaseline: 420,
  projectedPeak: 3800,
  projectedAvg: 2100,
  dailyProjection: [
    { day: "Pre-launch", visitors: 420 },
    { day: "Day 1", visitors: 1200 },
    { day: "Day 3", visitors: 1850 },
    { day: "Day 5", visitors: 2100 },
    { day: "Day 8", visitors: 2400 },
    { day: "Day 10", visitors: 2650 },
    { day: "Day 12", visitors: 3100 },
    { day: "Day 15", visitors: 3500 },
    { day: "Day 18 (Election)", visitors: 3800 },
  ],
};

// ── STARLING_VOTER_DEMO (dashboard-compatible shape) ─────────────────────────
// The existing STARLING_VOTER_DEMO above has different field names than what
// StarlingDashboard.tsx expects. We re-export a compatible version here.
// Dashboard needs: avgDbMatches, gender[], ageRanges[], topCities[], income[],
// homeowner.yesPct, married.yesPct, creditRating[]
export const STARLING_VOTER_DEMO_COMPAT = {
  avgDbMatches: 7.4,
  mobileReachPct: 93.8,
  emailReachPct: 98.8,
  gender: [
    { label: "Female", value: 56.3, pct: 56.3, color: "#7c3aed" },
    { label: "Male", value: 40.3, pct: 40.3, color: "#0891b2" },
    { label: "Unknown", value: 3.4, pct: 3.4, color: "#64748b" },
  ],
  ageRanges: [
    { label: "45–54", pct: 29.5, color: "#7c3aed" },
    { label: "55–64", pct: 34.9, color: "#0891b2" },
    { label: "65+", pct: 35.7, color: "#059669" },
  ],
  topCities: [
    { city: "Oklahoma City", pct: 18.0 },
    { city: "Tulsa", pct: 13.6 },
    { city: "Edmond", pct: 4.3 },
    { city: "Broken Arrow", pct: 4.0 },
    { city: "Norman", pct: 3.2 },
    { city: "Lawton", pct: 2.4 },
    { city: "Yukon", pct: 2.0 },
    { city: "Stillwater", pct: 1.6 },
    { city: "Claremore", pct: 1.5 },
    { city: "Owasso", pct: 1.4 },
    { city: "Enid", pct: 1.3 },
    { city: "Bartlesville", pct: 1.2 },
  ],
  income: [
    { label: "Under $20K", pct: 12.3, color: "#64748b" },
    { label: "$20K–$44K", pct: 19.8, color: "#0891b2" },
    { label: "$45K–$74K", pct: 23.1, color: "#7c3aed" },
    { label: "$75K–$99K", pct: 12.0, color: "#059669" },
    { label: "$100K–$149K", pct: 9.6, color: "#d97706" },
    { label: "$150K+", pct: 6.7, color: "#d97706" },
    { label: "Unknown", pct: 16.5, color: "#475569" },
  ],
  homeowner: { yesPct: 88.5, noPct: 11.5 },
  married: { yesPct: 57.7, noPct: 42.3 },
  creditRating: [
    { grade: "A", count: 5028, color: "#059669" },
    { grade: "B", count: 18298, color: "#0891b2" },
    { grade: "C", count: 17553, color: "#7c3aed" },
    { grade: "D", count: 14014, color: "#d97706" },
    { grade: "E–H", count: 23371, color: "#64748b" },
    { grade: "?", count: 47987, color: "#334155" },
  ],
};

// ── STARLING_EA_ADVANTAGE ─────────────────────────────────────────────────────
export const STARLING_EA_ADVANTAGE = [
  { icon: "🎯", title: "Voter-Level Precision", desc: "We match your voter file to streaming households. Your ad runs only in front of identified, named undecided Republican primary voters — not a general audience.", color: "#7c3aed" },
  { icon: "📊", title: "Behavioral Intelligence", desc: "We know what they are reading, searching, and watching since May 1. Content signals tell us which message will move each voter segment before you spend a dollar.", color: "#0891b2" },
  { icon: "📺", title: "74 Premium CTV Channels", desc: "From Fox News to Hallmark to ESPN — we reach your voters wherever they stream, across every device in the household, with unskippable 15-second spots.", color: "#059669" },
  { icon: "💰", title: "No Wasted Spend", desc: "Traditional broadcast TV buys the whole market. Exact Audience CTV buys only the voters you need. Every impression is a targeted, named voter impression.", color: "#d97706" },
  { icon: "⚡", title: "48-Hour Launch", desc: "Once the campaign is approved, we can have CTV running across all 74 channels within 48 hours. No long lead times, no broadcast commitments.", color: "#7c3aed" },
  { icon: "📈", title: "Real-Time Optimization", desc: "Daily performance data lets us shift budget toward the channels and voter segments converting fastest — so your last dollar works harder than your first.", color: "#0891b2" },
];

// ── STARLING_INTELLIGENCE ─────────────────────────────────────────────────────
export const STARLING_INTELLIGENCE = [
  { icon: "🔍", signal: "Searching 'Oklahoma AG candidates 2026'", detail: "High search volume for AG race candidate comparisons — voters are actively researching before deciding. Peak search activity: weekday evenings 7–10 PM." },
  { icon: "📰", signal: "Reading KFOR.com and News9.com", detail: "34% of the undecided universe visited KFOR.com in May; 31% visited News9.com. Local OKC news is the dominant news source for this voter segment." },
  { icon: "📺", signal: "Streaming local news on CTV", detail: "67% of the undecided universe watches local news via streaming (CTV). They have cut the cord but still consume local news — making CTV the ideal channel." },
  { icon: "👍", signal: "Engaging with conservative Facebook content", detail: "44% of the undecided universe engaged with conservative political video content on Facebook in May. Facebook video is the #2 channel after CTV for this audience." },
  { icon: "🎬", signal: "Watching Fox News and Newsmax streaming", detail: "41% stream Fox News; 28% stream Newsmax. These voters are ideologically conservative and respond to anti-establishment, pro-Trump messaging." },
  { icon: "🌐", signal: "Visiting jeffstarling.com", detail: "Voters who visit jeffstarling.com spend an average of 2 min 47 sec on the site — indicating high intent. Retargeting these visitors with CTV ads is highest-ROI spend." },
  { icon: "⚖️", signal: "Researching Echols' record", detail: "Significant search volume for 'Jon Echols tax increases' and 'Echols RINO' — the contrast message is already resonating organically. Paid media amplifies it." },
  { icon: "📱", signal: "93.8% reachable on mobile", detail: "Nearly every voter in the undecided universe has a verified mobile number on file. Pre-roll YouTube and Facebook video reach them on mobile during commute hours." },
];

// ── STARLING_DIGITAL_CHANNELS ─────────────────────────────────────────────────
export const STARLING_DIGITAL_CHANNELS = [
  { name: "Google Search Retargeting", desc: "Capture voters actively searching AG race terms", color: "#7c3aed", type: "Search" },
  { name: "Google Display Network", desc: "Banner ads across 2M+ websites and apps", color: "#0891b2", type: "Display" },
  { name: "YouTube Pre-Roll", desc: "15-sec unskippable before political/news content", color: "#059669", type: "Video" },
  { name: "Facebook Video", desc: "In-feed video targeting identified voter list", color: "#d97706", type: "Social" },
  { name: "Instagram Video", desc: "Reels and Stories targeting 45–65+ voters", color: "#7c3aed", type: "Social" },
  { name: "Programmatic Display", desc: "DSP targeting across premium news sites", color: "#0891b2", type: "Programmatic" },
];

// ── STARLING_CREATIVES ────────────────────────────────────────────────────────
export const STARLING_CREATIVES = [
  { title: "The Contrast", hook: "Jon Echols has been a career politician for 14 years. He voted to raise your taxes. He took money from liberal trial lawyers. Jeff Starling is not a politician — he is a practicing attorney who has never taken a dime from special interests.", cta: "Oklahoma needs an AG who works for you, not the establishment." },
  { title: "The Outsider", hook: "While career politicians like Jon Echols were raising taxes and cutting deals in Oklahoma City, Jeff Starling was in the courtroom — fighting for Oklahomans. That is the difference between a politician and a prosecutor.", cta: "Jeff Starling. The AG Oklahoma deserves." },
  { title: "Law & Order", hook: "Oklahoma's crime rate is rising. Career politicians talk about it. Jeff Starling has spent his career prosecuting it. As Attorney General, he will bring the same relentless focus to protecting Oklahoma families.", cta: "A real attorney. A real conservative. Jeff Starling for AG." },
  { title: "The Closer", hook: "On June 16th, Oklahoma Republicans have a choice: a 14-year career politician who raised your taxes — or a practicing attorney who has never held office and will never owe anyone a favor. The choice is clear.", cta: "Vote Jeff Starling. Oklahoma's next Attorney General." },
];
